parameters:
  problematic.acl_manager.class: Ojs\CoreBundle\Acl\AclChainManager
  security.acl.dbal.provider.class: Ojs\CoreBundle\Acl\Dbal\MutableAclProvider
  security.acl.security_identity_retrieval_strategy.class: Ojs\CoreBundle\Acl\SecurityIdentityRetrievalStrategy
  security.acl.object_identity_retrieval_strategy.class: Ojs\CoreBundle\Acl\ObjectIdentityRetrievalStrategy
  ojs_core.sitemap.listener.class: Ojs\CoreBundle\EventListener\SitemapListener
  prezent_doctrine_translatable.listener.class: Ojs\CoreBundle\EventListener\TranslatableCacheListener
services:
  app.routing_loader:
    class: Ojs\CoreBundle\Routing\ThirdPartyRouteLoader
    arguments: ["@kernel", "@file_locator"]
    tags:
      - { name: routing.loader }

  security.authorization_checker:
    class: Ojs\CoreBundle\Acl\AuthorizationChecker
    arguments:
      - "@security.token_storage"
      - "@security.authentication.manager"
      - "@security.access.decision_manager"
      - "%security.access.always_authenticate_before_granting%"

  security.acl.security_identity_retrieval_strategy:
    class: "%security.acl.security_identity_retrieval_strategy.class%"
    arguments: ["@security.role_hierarchy", "@security.authentication.trust_resolver", "@ojs.journal_service"]

  ojs_mailer:
    class: Ojs\CoreBundle\Service\OjsMailer
    arguments:
      - "@mailer"
      - "%system_email%"
      - "%mailer_name%"
      - "@doctrine"
      - "@security.token_storage"
      - "%locale%"

  ojs_locale.locale_listener:
    class: Ojs\CoreBundle\Service\LocaleListener
    arguments: ["%kernel.default_locale%"]
    tags:
      - { name: kernel.event_subscriber }

  ojs.twig.ojs_extension:
    class: Ojs\CoreBundle\Service\Twig\OjsExtension
    arguments:
      - "@doctrine.orm.entity_manager"
      - "@router"
      - "@translator"
      - "@ojs.journal_service"
      - "@security.token_storage"
      - "@session"
      - "@request_stack"
      - "%cms_show_routes%"
      - "@event_dispatcher"
    tags:
      - { name: twig.extension }

  ojs.twig.display_extension:
    class: Ojs\CoreBundle\Service\Twig\DisplayExtension
    arguments:
      - "@translator"
      - "@annotation_reader"
      - "@liip_imagine.twig.extension"
    tags:
      - { name: twig.extension }

  ojs.twig.field_display_extension:
    class: Ojs\CoreBundle\Service\Twig\FieldDisplayExtension
    arguments:
      - "@translator"
      - "@annotation_reader"
      - "@liip_imagine.twig.extension"
      - "@router"
    tags:
      - { name: twig.extension }

  ojs.twig.action_extension:
    class: Ojs\CoreBundle\Service\Twig\ActionExtension
    arguments:
      - "@translator"
    tags:
      - { name: twig.extension }

  ojs.article_service:
    class: Ojs\CoreBundle\Service\ArticleService
    arguments: [ "@doctrine.orm.entity_manager","@ojs.journal_service", "@session" ]

  ojs.alice.provider:
    class: Ojs\CoreBundle\Service\AliceDataProvider
    arguments: [ "%defaultPublisherSlug%", "%system_email%" ]
    tags:
      -  { name: h4cc_alice_fixtures.provider }

  grid_action:
    class: Ojs\CoreBundle\Service\GridAction
    arguments: ["@security.csrf.token_manager", "@translator", "@ojs.cms.twig.post_extension"]

  form.type.tags:
    class: Ojs\CoreBundle\Form\Type\TagsType
    arguments: [ "@router", "@translator" ]
    tags:
      - { name: form.type, alias: tags }

  form.type.extended_entity:
      class: Ojs\CoreBundle\Form\Type\ExtendedEntityType
      arguments: ["@property_accessor"]
      tags:
          - { name: form.type, alias: extended_entity }

  form.type.purified_textarea:
      class: Ojs\CoreBundle\Form\Type\PurifiedTextareaType
      tags:
        - { name: form.type, alias: purified_textarea }

  ojs_core.search_manager:
    class: Ojs\CoreBundle\Service\Search\SearchManager
    arguments: ["@translator", "@router", "@request_stack", "@ojs_core.search.native_query_generator"]

  ojs_core.search.native_query_generator:
    class: Ojs\CoreBundle\Service\Search\NativeQueryGenerator
    arguments: []

  ojs_api_handler_helper:
    class: Ojs\CoreBundle\Service\ApiHandlerHelper
    arguments: ['@kernel', '@annotation_reader', '@liip_imagine.twig.extension', '@request_stack']

  kernel.listener.command_dispatch:
    class: Ojs\CoreBundle\EventListener\ConsoleExceptionListener
    arguments:
      logger: "@logger"
    tags:
      - { name: kernel.event_listener, event: console.exception }

  core.event_listener:
    class: Ojs\CoreBundle\EventListener\CoreEventListener
    arguments: ["@router", "@doctrine.orm.entity_manager", "@ojs_mailer"]
    tags:
      - { name: kernel.event_subscriber }

  core.acl_fixer:
    class: Ojs\CoreBundle\Service\AclFixer
    arguments: ["@doctrine", "@problematic.acl_manager"]

  ojs_core.delete.service:
    class: Ojs\CoreBundle\Service\DeleteService
    arguments: ["@doctrine", "@annotation_reader", "@translator", %kernel.root_dir%, %kernel.bundles%]

  ojs_core.sitemap.listener:
    class: "%ojs_core.sitemap.listener.class%"
    arguments: ["@router", "@doctrine.orm.entity_manager"]
    tags: [{name: "presta.sitemap.listener"}]

  app.exception_listener:
    class: Ojs\CoreBundle\Listeners\ExceptionListener
    arguments: ["@router", "@session", "@translator", "@request_stack"]
    tags:
        - { name: kernel.event_listener, event: kernel.exception }

  #Look {http://docs.doctrine-project.org/projects/doctrine-common/en/latest/reference/caching.html}
  file_cache:
      class: Doctrine\Common\Cache\FilesystemCache
      arguments: ['%kernel.cache_dir%']

  array_cache:
      class: Doctrine\Common\Cache\ArrayCache

  ojs_core.mail.event_chain:
    class: Ojs\CoreBundle\Events\Chain\MailEventChain

  ojs_core.core_events:
    class: Ojs\CoreBundle\Events\CoreEvents
    tags:
      - { name: ojs.mail.event}

  ojs_core.twig_events:
    class: Ojs\CoreBundle\Events\TwigEvents
