Ojs\JournalBundle\Entity\ArticleAuthor:
    type: entity
    table: article_author
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        authorOrder:
            type: integer
            column: author_order
        createdBy:
           type: string
           gedmo:
             blameable:
               on: create
        updatedBy:
           type: string
           gedmo:
             blameable:
               on: update
    manyToOne:
        author:
            targetEntity: Author
            inversedBy: articleAuthors
            joinColumn:
                name: author_id
                referencedColumnName: id
        article:
            targetEntity: Article
            inversedBy: articleAuthors
            joinColumn:
                name: article_id
                referencedColumnName: id
    lifecycleCallbacks: {  }
