Ojs\JournalBundle\Entity\Author:
    type: entity
    table: author
    repositoryClass: Ojs\JournalBundle\Entity\AuthorRepository
    oneToMany:
        articleAuthors:
            targetEntity: ArticleAuthor
            mappedBy: author
    manyToOne:
          institution:
                targetEntity: Institution
                joinColumn:
                    name: institution_id
                    referencedColumnName: id
                inversedBy: authors
          user:
                targetEntity: Ojs\UserBundle\Entity\User
                joinColumn:
                  name: user_id
                  referencedColumnName: id
          country:
                targetEntity: Okulbilisim\LocationBundle\Entity\Location
                joinColumn:
                  name: country_id
                  referencedColumnName: id
          city:
                targetEntity: Okulbilisim\LocationBundle\Entity\Location
                joinColumn:
                  name: city_id
                  referencedColumnName: id
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        firstName:
            type: string
            length: 255
            column: first_name
            gedmo:
                - versioned
        middleName:
            type: string
            length: 255
            column: middle_name
            nullable: TRUE
            gedmo:
                - versioned
        lastName:
            type: string
            length: 255
            column: last_name
            gedmo:
                - versioned
        title:
            type: string
            nullable: true
            length: 255
        firstNameTransliterated:
            type: string
            length: 255
            column: first_name_transliterated
            nullable: TRUE
        middleNameTransliterated:
            type: string
            length: 255
            column: middle_name_transliterated
            nullable: TRUE
        lastNameTransliterated:
            type: string
            length: 255
            column: last_name_transliterated
            nullable: TRUE
        initials:
            type: string
            length: 255
            nullable: true
        orcid:
            type: string
            length: 255
            nullable: true
        email:
            type: string
            length: 255
            nullable: TRUE
        url:
            type: string
            nullable: true
        phone:
            type: string
            nullable: true
        fax:
            type: string
            nullable: true
        address:
            type: text
            nullable: true
        billing_address:
            type: text
            nullable: true
        locales:
            type: string
            nullable: true
        institutionId:
            type: integer
            nullable: true
            column: institution_id
            nullable: TRUE
        summary:
            type: text
            nullable: TRUE
            gedmo:
                - translatable
        created:
            type: datetime
            gedmo:
              timestampable:
                on: create
        updated:
            type: datetime
            gedmo:
              timestampable:
                on: update
        deletedAt:
            type: date
            nullable: true
        createdBy:
           type: string
           gedmo:
             blameable:
               on: create
        updatedBy:
           type: string
           gedmo:
             blameable:
               on: update
    gedmo:
        soft_deleteable:
          field_name: deletedAt
          time_aware: false
        translation:
            locale: locale
        loggable: true
    lifecycleCallbacks: {  }