Ojs\JournalBundle\Entity\Board:
    type: entity
    table: board
    repositoryClass: Ojs\JournalBundle\Entity\BoardRepository
    cache:
        usage: NONSTRICT_READ_WRITE
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    manyToOne:
        journal:
            targetEntity: Journal
            joinColumn:
              name: journal_id
              referencedColumnName: id
            inversedBy: boards
            cascade: ["persist","merge"]
    oneToMany:
        boardMembers:
            targetEntity: BoardMember
            mappedBy: board
            cascade: ["persist", "merge"]
            fetch: EXTRA_LAZY
    fields:
    lifecycleCallbacks: {  }
    gedmo:
        loggable: true
