Ojs\JournalBundle\Entity\Citation:
    type: entity
    table: citation
    #repositoryClass: Ojs\JournalBundle\Entity\CitationRepository
    oneToMany:
        settings:
          targetEntity: Ojs\JournalBundle\Entity\CitationSetting
          mappedBy: citation
          cascade: ["persist", "merge"]
          fetch: EXTRA_LAZY
    manyToMany:
        articles:
          targetEntity: Article
          mappedBy: citations
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        raw:
            type: text
            gedmo:
                - translatable
                - versioned
        type:
            type: string
            length: 20
            gedmo:
                - versioned
            nullable: true
        orderNum:
            type: integer
            column: order_num
            gedmo:
                - versioned
        created:
            type: datetime
            gedmo:
              timestampable:
                on: create
        updated:
            type: datetime
            gedmo:
              timestampable:
                on: update
        deletedAt:
            type: date
            nullable: true
        createdBy:
           type: string
           gedmo:
             blameable:
               on: create
        updatedBy:
           type: string
           gedmo:
             blameable:
               on: update
    gedmo:
       soft_deleteable:
         field_name: deletedAt
         time_aware: false
       translation:
           locale: locale
       loggable: true
    lifecycleCallbacks: {  }
