Ojs\JournalBundle\Entity\Institution:
    type: entity
    table: institution
    repositoryClass: Ojs\JournalBundle\Entity\InstitutionRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    oneToMany:
        journals:
            targetEntity: Journal
            mappedBy: institution
            cascade: ["persist", "merge"]
            fetch: LAZY
        authors:
            targetEntity: Author
            mappedBy: institution
            cascade: ["persist", "merge"]
            fetch: EXTRA_LAZY
        children:
            targetEntity: Institution
            mappedBy: parent
            orderBy:
                  lft: ASC
        institutionThemes:
            targetEntity: Ojs\JournalBundle\Entity\InstitutionTheme
            mappedBy: institution
        institutionDesigns:
            targetEntity: Ojs\JournalBundle\Entity\InstitutionDesign
            mappedBy: institution
    manyToMany:
        institutionManagers:
            targetEntity: Ojs\UserBundle\Entity\User
            joinTable:
                name: institution_managers
                joinColumns:
                    institution_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    user_id:
                        referencedColumnName: id
    manyToOne:
        institution_type:
            targetEntity: Ojs\JournalBundle\Entity\InstitutionTypes
            joinColumn:
                name: institution_type_id
                referencedColumnName: id
            inversedBy: institutions
        country:
            targetEntity: Ojs\LocationBundle\Entity\Country
            joinColumn:
                  name: country_id
                  referencedColumnName: id
        city:
            targetEntity: Ojs\LocationBundle\Entity\Province
            joinColumn:
                  name: city_id
                  referencedColumnName: id
        parent:
              targetEntity: Institution
              inversedBy: children
              joinColumn:
                    name: parent_id
                    referencedColumnName: id
                    onDelete: CASCADE
              gedmo:
                - treeParent
        theme:
          targetEntity: Ojs\JournalBundle\Entity\InstitutionTheme
          joinColumn:
            name: theme_id
            referencedColumnName: id
          inversedBy: institutions
        design:
          targetEntity: Ojs\JournalBundle\Entity\InstitutionDesign
          joinColumn:
            name: design_id
            referencedColumnName: id
          inversedBy: institutions
    fields:
        lft:
           type: integer
           gedmo:
             - treeLeft
        rgt:
           type: integer
           gedmo:
             - treeRight
        root:
           type: integer
           nullable: true
           gedmo:
             - treeRoot
        lvl:
           type: integer
           gedmo:
             - treeLevel
        institution_type_id:
            type: integer
            nullable: true
        name:
            type: string
            length: 255
            gedmo:
                - versioned
        slug:
            type: string
            length: 255
            unique: true
            gedmo:
                versioned : ~
                slug:
                    seperator: _
                    fields:
                      - name
        address:
            type: text
            nullable: TRUE
            gedmo:
                - versioned
        addressLat:
            type: string
            length: 255
            column: address_lat
            nullable: TRUE
            gedmo:
                  - versioned
        addressLong:
            type: string
            length: 255
            column: address_long
            nullable: TRUE
            gedmo:
                - versioned
        phone:
            type: string
            length: 255
            nullable: TRUE
            gedmo:
                - versioned
        fax:
            type: string
            length: 255
            nullable: TRUE
            gedmo:
                - versioned
        email:
            type: string
            length: 255
            nullable: TRUE
            gedmo:
                - versioned
        domain:
            type: string
            length: 255
            nullable: TRUE
            gedmo:
                - versioned
        url:
            type: string
            length: 255
            nullable: TRUE
            gedmo:
                - versioned
        themeId:
            type: integer
            column: theme_id
            nullable: true
            options:
                default: 0
            gedmo:
                  - versioned
        designId:
            type: integer
            column: design_id
            nullable: true
            options:
                default: 0
            gedmo:
                  - versioned
        wiki:
            type: string
            length: 255
            nullable: TRUE
            gedmo:
                  - versioned
        #IMAGES
        logo:
            type: string
            length: 255
            nullable: TRUE
            gedmo:
                - versioned
        header:
            type: string
            length: 255
            nullable: true
            gedmo:
                - versioned
        #IMAGES#
        created:
            type: datetime
            gedmo:
              timestampable:
                on: create
        updated:
            type: datetime
            gedmo:
              timestampable:
                on: update
        deletedAt:
            type: date
            nullable: true
        createdBy:
           type: string
           gedmo:
             blameable:
               on: create
           nullable: true
        updatedBy:
           type: string
           gedmo:
             blameable:
               on: update
           nullable: true
        tags:
            type: string
            nullable: true
            gedmo:
                  - versioned
        verified:
            type: boolean
            gedmo:
                  - versioned
        status:
            type: integer

    gedmo:
        soft_deleteable:
          field_name: deletedAt
          time_aware: false
        loggable: true
        tree:
             type: nested
    lifecycleCallbacks: {  }
