Ojs\JournalBundle\Entity\Issue:
    type: entity
    table: issue
    repositoryClass: Ojs\JournalBundle\Entity\IssueRepository
    manyToMany:
        sections:
            targetEntity: JournalSection
            #inversedBy: issues
            joinTable:
              inverseJoinColumns:
                section_id:
                  referencedColumnName: id
              joinColumns:
                issue_id:
                  referencedColumnName: id
              name: issue_journal_section
              cascade: ["persist", "merge"]
              fetch: LAZY
    oneToMany:
        articles:
          targetEntity: Article
          mappedBy: issue
          cascade: ["persist", "merge"]
          fetch: LAZY
    manyToOne:
      journal:
          targetEntity: Journal
          joinColumn:
            name: journal_id
            referencedColumnName: id
          inversedBy: issues
          cascade: ["persist","merge"]
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        journalId:
            type: integer
            column: journal_id
            gedmo:
                - versioned
        volume:
            type: string
            length: 255
            gedmo:
                - versioned
        number:
            type: string
            length: 255
            gedmo:
                - versioned
        title:
            type: string
            length: 255
            gedmo:
                - translatable
                - versioned
        cover:
            type: string
            column: cover
            length: 255
            nullable: TRUE
            gedmo:
                - translatable
                - versioned
        cover_options:
            type: string
            nullable: true
        header:
            type: string
            length: 255
            nullable: true
        header_options:
            type: string
            nullable: true
        special:
            type: boolean
            column: special
            nullable: TRUE
            oprions:
                default: TRUE
            gedmo:
                - versioned
        description:
            type: text
            nullable: TRUE
            gedmo:
                - translatable
        year:
            type: string
            length: 255
            gedmo:
                - versioned
        datePublished:
            type: datetime
            column: date_published
        created:
            type: datetime
            gedmo:
              timestampable:
                on: create
        updated:
            type: datetime
            gedmo:
              timestampable:
                on: update
        deletedAt:
            type: date
            nullable: true
        createdBy:
           type: string
           nullable: true
           gedmo:
             blameable:
               on: create
        updatedBy:
           type: string
           nullable: true
           gedmo:
             blameable:
               on: update
        tags:
            type: string
            nullable: true
    gedmo:
        soft_deleteable:
          field_name: deletedAt
          time_aware: false
        translation:
            locale: locale
        loggable: true
    lifecycleCallbacks: {  }
