Ojs\JournalBundle\Entity\IssueFile:
    type: entity
    table: issue_file
    repositoryClass: Ojs\JournalBundle\Entity\IssueFileRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    manyToOne:
        issue:
            targetEntity: Issue
            inversedBy: issueFiles
            joinColumn:
                name: issue_id
                referencedColumnName: id
            cascade: ["persist"]
    oneToMany:
        statistics:
            targetEntity: Ojs\AnalyticsBundle\Entity\IssueFileStatistic
            mappedBy: issueFile
            cascade: ["persist"]
    fields:
        type:
            type: integer
            nullable: TRUE
        file:
            type: string
            gedmo:
                - versioned
        version:
            type: integer
            nullable: true
            options:
              default: 0
        keywords:
            type: string
            length: 255
            nullable: TRUE
            gedmo:
                - versioned
        langCode:
            column: lang_code
            type: string
            length: 50
            nullable: TRUE
            gedmo:
                - versioned
        updated:
            type: datetime
            gedmo:
              timestampable:
                on: update
        deletedAt:
            type: date
            nullable: true
        createdBy:
           type: string
           gedmo:
             blameable:
               on: create
        updatedBy:
           type: string
           nullable: true
           gedmo:
             blameable:
               on: update
    gedmo:
        loggable: true
        soft_deleteable:
            field_name: deletedAt
            time_aware: false
    lifecycleCallbacks: {  }
