Ojs\JournalBundle\Entity\Journal:
  type: entity
  table: journal
  repositoryClass: Ojs\JournalBundle\Entity\JournalRepository
  cache:
    usage: NONSTRICT_READ_WRITE
  manyToOne:
    publisher:
      targetEntity: Publisher
      cascade: ["persist"]
      cache:
          usage: NONSTRICT_READ_WRITE
          region: journal
      joinColumn:
        name: publisher_id
        referencedColumnName: id
      inversedBy: journals
    theme:
      targetEntity: Ojs\JournalBundle\Entity\JournalTheme
      joinColumn:
        name: theme_id
        referencedColumnName: id
    design:
      targetEntity: Ojs\JournalBundle\Entity\Design
      joinColumn:
        nullable: true
        name: design_id
        referencedColumnName: id
    country:
      targetEntity: BulutYazilim\LocationBundle\Entity\Country
      joinColumn:
        name: country_id
        referencedColumnName: id
    mandatoryLang:
      targetEntity: Ojs\JournalBundle\Entity\Lang
      joinColumn:
        name: mandatory_lang_id
        referencedColumnName: id
  oneToMany:
    articles:
      targetEntity: Article
      mappedBy: journal
      cascade: ["persist", "merge", "remove"]
      fetch: LAZY
      cache:
        usage: NONSTRICT_READ_WRITE
    issues:
      targetEntity: Issue
      mappedBy: journal
      cascade: ["persist", "merge", "remove"]
      fetch: EXTRA_LAZY
      cache:
        usage: NONSTRICT_READ_WRITE
    boards:
      targetEntity: Board
      mappedBy: journal
      cascade: ["persist", "merge", "remove"]
      fetch: EXTRA_LAZY
      orderBy: { 'boardOrder': 'ASC' }
      cache:
        usage: NONSTRICT_READ_WRITE
    sections:
      targetEntity: Section
      mappedBy: journal
      cascade: ["persist", "merge", "remove"]
      fetch: LAZY
      cache:
        usage: NONSTRICT_READ_WRITE
    journalIndexs:
      targetEntity: Ojs\JournalBundle\Entity\JournalIndex
      mappedBy: journal
      cascade: ["persist", "remove"]
      fetch: EXTRA_LAZY
      cache:
        usage: NONSTRICT_READ_WRITE
    submissionChecklist:
      targetEntity: Ojs\JournalBundle\Entity\SubmissionChecklist
      mappedBy: journal
      cascade: ["persist", "remove"]
      fetch: EXTRA_LAZY
      cache:
        usage: NONSTRICT_READ_WRITE
    journalSubmissionFiles:
      targetEntity: Ojs\JournalBundle\Entity\JournalSubmissionFile
      mappedBy: journal
      cascade: ["persist", "remove"]
      fetch: EXTRA_LAZY
      cache:
        usage: NONSTRICT_READ_WRITE
    journalUsers:
      targetEntity: Ojs\JournalBundle\Entity\JournalUser
      mappedBy: journal
      fetch: EXTRA_LAZY
      cascade: ["remove"]
    journalContacts:
      targetEntity: Ojs\JournalBundle\Entity\JournalContact
      mappedBy: journal
      cascade: ["persist", "remove"]
      cache:
        usage: NONSTRICT_READ_WRITE
    statistics:
      targetEntity: Ojs\AnalyticsBundle\Entity\JournalStatistic
      mappedBy: journal
      cascade: ["persist", "remove"]
    journalApplicationUploadFiles:
      targetEntity: Ojs\JournalBundle\Entity\JournalApplicationUploadFile
      mappedBy: journal
      cascade: ["remove"]
  manyToMany:
    languages:
      targetEntity: Ojs\JournalBundle\Entity\Lang
      cascade: ["persist"]
      joinTable:
        inverseJoinColumns:
          language_id:
            referencedColumnName: id
            onDelete: CASCADE
        joinColumns:
          journal_id:
            referencedColumnName: id
            onDelete: CASCADE
        name: journal_language
      fetch: EXTRA_LAZY
      cache:
        usage: NONSTRICT_READ_WRITE
    periods:
      targetEntity: Ojs\JournalBundle\Entity\Period
      cascade: ["persist"]
      joinTable:
        inverseJoinColumns:
          period_id:
            referencedColumnName: id
            onDelete: CASCADE
        joinColumns:
          journal_id:
            referencedColumnName: id
            onDelete: CASCADE
        name: journal_period
      cache:
        usage: NONSTRICT_READ_WRITE
    subjects:
      targetEntity: Ojs\JournalBundle\Entity\Subject
      cascade: ["persist"]
      mappedBy: null
      inversedBy: journals
      joinTable:
        name: journal_subject
        joinColumns:
          journal_id:
            referencedColumnName: id
            onDelete: CASCADE
        inverseJoinColumns:
          subject_id:
            referencedColumnName: id
            onDelete: CASCADE
      cache:
        usage: NONSTRICT_READ_WRITE
    bannedUsers:
      targetEntity: Ojs\UserBundle\Entity\User
      cascade: ["persist"]
      inversedBy: restrictedJournals
      joinTable:
        name: journal_banned_users
        joinColumns:
          journal_id:
            referencedColumnName: id
            onDelete: CASCADE
        inverseJoinColumns:
          user_id:
            referencedColumnName: id
            onDelete: CASCADE
      cache:
        usage: NONSTRICT_READ_WRITE
  id:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO
  fields:
    titleTransliterated:
      type: string
      length: 255
      column: title_transliterated
      nullable: true
      gedmo:
        - versioned
    path:
      type: string
      length: 255
      column: path
      nullable: true
      gedmo:
        - versioned
    domain:
      type: string
      length: 255
      column: domain
      nullable: true
      gedmo:
        - versioned
    issn:
      type: string
      length: 11
      nullable: true
      gedmo:
        - versioned
    totalArticleView:
      type: integer
      nullable: true
      column: total_article_view
      options:
        default: 0
    eissn:
      type: string
      length: 11
      nullable: true
      gedmo:
        - versioned
    founded:
      type: datetime
      column: founded
      nullable: true
    endingDate:
      type: datetime
      column: ending_date
      nullable: true
    url:
      type: string
      length: 255
      nullable: true
      gedmo:
        - versioned
    address:
      type: string
      length: 255
      nullable: true
      gedmo:
        - versioned
    phone:
      type: string
      length: 255
      nullable: true
      gedmo:
        - versioned
    email:
      type: string
      length: 255
      nullable: true
      gedmo:
        - versioned
    status:
      type: integer
      gedmo:
          - versioned
      nullable: true
    accessModal:
      type: integer
      gedmo:
          - versioned
      nullable: true
      column: access_model
    image:
      type: string
      length: 255
      column: image
      nullable: true
      gedmo:
        - versioned
    journalIndexesBag:
      type: string
      length: 255
      column: journal_indexes_bag
      nullable: true
      gedmo:
        - versioned
    header:
      type: string
      length: 255
      nullable: true
      gedmo:
        - versioned
    logo:
      type: string
      length: 255
      nullable: true
      gedmo:
        - versioned
    languageCodeSet:
      languages_code_set:
      type: string
      length: 30
      nullable: true
      gedmo:
        - versioned
    googleAnalyticsId:
      type: string
      length: 50
      nullable: true
      column: google_analytics_id
    slug:
      type: string
      length: 255
      unique: false
      gedmo:
        versioned : ~
        slug:
          seperator: _
          fields:
            - id
    configured:
      column: is_configured
      type: boolean
      nullable: TRUE
      gedmo:
        - versioned
    created:
      type: datetime
      gedmo:
        timestampable:
          on: create
    updated:
      type: datetime
      gedmo:
        timestampable:
          on: update
      nullable: true
    deletedAt:
      type: date
      nullable: true
    createdBy:
      type: string
      gedmo:
       blameable:
         on: create
      nullable: true
    updatedBy:
      type: string
      gedmo:
        blameable:
          on: update
      nullable: true
    tags:
      type: string
      nullable: true
      gedmo:
        - versioned
    setupFinished:
      type: boolean
      nullable: true
      column: setup_finished
    footerText:
      type: text
      nullable: true
      column: footer_text
      gedmo:
        - versioned
    note:
      type: text
      nullable: true
      column: note
      gedmo:
        - versioned
    viewCount:
      type: integer
      nullable: true
      column: view_count
      options:
        default: 0
    downloadCount:
      type: integer
      nullable: true
      column: download_count
      options:
        default: 0
    printed:
      type: boolean
      nullable: true
      gedmo:
        - versioned
  gedmo:
    soft_deleteable:
      field_name: deletedAt
      time_aware: false
    loggable: true
  lifecycleCallbacks: {  }
