Ojs\JournalBundle\Entity\JournalContact:
    type: entity
    table: journal_contact
    repositoryClass: Ojs\JournalBundle\Entity\JournalContactRepository
    cache:
        usage: NONSTRICT_READ_WRITE
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    manyToOne:
          title:
                targetEntity: Ojs\JournalBundle\Entity\PersonTitle
                joinColumn:
                  name: title_id
                  referencedColumnName: id
          country:
                targetEntity: BulutYazilim\LocationBundle\Entity\Country
                joinColumn:
                  name: country_id
                  referencedColumnName: id
          journal:
                targetEntity: Ojs\JournalBundle\Entity\Journal
                joinColumn:
                  name: journal_id
                  referencedColumnName: id
                inversedBy: journalContacts
          institution:
                targetEntity: Ojs\JournalBundle\Entity\Institution
                joinColumn:
                  name: institution_id
                  referencedColumnName: id
                inversedBy: institutionContacts
          contactType:
                targetEntity: Ojs\JournalBundle\Entity\ContactTypes
                joinColumn:
                  name: contact_type_id
                  referencedColumnName: id
    fields:
        fullName:
            type: string
            length: 255
            column: first_name
            gedmo:
                - versioned
            nullable: true
        affiliation:
            type: text
            nullable: true
            gedmo:
                - versioned
        email:
            type: string
            length: 255
            gedmo:
                - versioned
            nullable: true
        phone:
            type: string
            length: 255
            nullable: TRUE
            gedmo:
                - versioned
        address:
            type: text
            nullable: TRUE
            gedmo:
                - versioned
        city:
            type: text
            nullable: true
        created:
            type: datetime
            gedmo:
              timestampable:
                on: create
        updated:
            type: datetime
            gedmo:
              timestampable:
                on: update
        deletedAt:
            type: date
            nullable: true
        createdBy:
           type: string
           gedmo:
             blameable:
               on: create
        updatedBy:
           type: string
           nullable: true
           gedmo:
             blameable:
               on: update
        tags:
            type: string
            nullable: true
            gedmo:
                - versioned
    gedmo:
        soft_deleteable:
          field_name: deletedAt
          time_aware: false
        loggable: true
    lifecycleCallbacks: {  }
