Ojs\JournalBundle\Entity\Journal:
    type: entity
    table: journal
    repositoryClass: Ojs\JournalBundle\Entity\JournalRepository
    manyToOne:
        institution:
          targetEntity: Institution
          joinColumn:
            name: institution_id
            referencedColumnName: id
          inversedBy: journals
        theme:
          targetEntity: Ojs\JournalBundle\Entity\JournalTheme
          joinColumn:
            name: theme_id
            referencedColumnName: id
          inversedBy: journals
        design:
          targetEntity: Ojs\JournalBundle\Entity\JournalDesign
          joinColumn:
            name: design_id
            referencedColumnName: id
          inversedBy: journals
        country:
          targetEntity: Ojs\LocationBundle\Entity\Country
          joinColumn:
            name: country_id
            referencedColumnName: id
        mandatoryLang:
            targetEntity: Ojs\JournalBundle\Entity\Lang
            joinColumn:
              name: mandatory_lang_id
              referencedColumnName: id
    oneToMany:
        settings:
            targetEntity: JournalSetting
            mappedBy: journal
            cascade: ["ALL"]
            indexBy: setting
            fetch: EXTRA_LAZY
        articles:
            targetEntity: Article
            mappedBy: journal
            cascade: ["persist", "merge"]
            fetch: LAZY
        issues:
            targetEntity: Issue
            mappedBy: journal
            cascade: ["persist", "merge"]
            fetch: EXTRA_LAZY
        boards:
            targetEntity: Board
            mappedBy: journal
            cascade: ["persist", "merge"]
            fetch: EXTRA_LAZY
        sections:
            targetEntity: JournalSection
            mappedBy: journal
            cascade: ["persist", "merge"]
            fetch: LAZY
        journalThemes:
            targetEntity: JournalTheme
            mappedBy: journal
        journalDesigns:
            targetEntity: JournalDesign
            mappedBy: journal
        journals_indexs:
            targetEntity: Ojs\JournalBundle\Entity\JournalsIndex
            mappedBy: journal
            cascade: ["all"]
            fetch: EXTRA_LAZY
        submissionChecklist:
            targetEntity: Ojs\JournalBundle\Entity\SubmissionChecklist
            mappedBy: journal
            cascade: ["all"]
            fetch: EXTRA_LAZY
        submissionFile:
            targetEntity: Ojs\JournalBundle\Entity\SubmissionFile
            mappedBy: journal
            cascade: ["all"]
            fetch: EXTRA_LAZY
        journalUsers:
            targetEntity: Ojs\JournalBundle\Entity\JournalUser
            mappedBy: journal
            fetch: EXTRA_LAZY
        journalContacts:
            targetEntity: Ojs\JournalBundle\Entity\JournalContact
            mappedBy: journal
            cascade: ["persist"]
        statistics:
              targetEntity: Ojs\AnalyticsBundle\Entity\JournalStatistic
              mappedBy: journal
              cascade: ["persist"]
    manyToMany:
        languages:
              targetEntity: Lang
              joinTable:
                inverseJoinColumns:
                  language_id:
                    referencedColumnName: id
                joinColumns:
                  journal_id:
                    referencedColumnName: id
                name: journal_language
              fetch: EXTRA_LAZY
        subjects:
            targetEntity: Subject
            cascade: ["persist"]
            mappedBy: null
            inversedBy: journals
            joinTable:
                name: journal_subject
                joinColumns:
                    -
                        name: journal_id
                        referencedColumnName: id
                        onDelete: CASCADE
                inverseJoinColumns:
                    -
                        name: subject_id
                        referencedColumnName: id
                        onDelete: CASCADE
        bannedUsers:
            targetEntity: Ojs\UserBundle\Entity\User
            cascase: ["all"]
            inversedBy: restrictedJournals
            joinTable:
                name: journal_banned_users
                joinColumns:
                    -
                        name: journal_id
                        referencedColumnName: id
                        onDelete: CASCADE
                inverseJoinColumns:
                    -
                        name: user_id
                        referencedColumnName: id
                        onDelete: CASCADE
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        titleAbbr:
            type: string
            length: 255
            column: title_abbr
            nullable: true
            gedmo:
                  - versioned
        titleTransliterated:
            type: string
            length: 255
            column: title_transliterated
            nullable: true
            gedmo:
                  - versioned
        path:
            type: string
            length: 255
            column: path
            nullable: true
            gedmo:
                - versioned
        domain:
            type: string
            length: 255
            column: domain
            nullable: true
            gedmo:
                - versioned
        issn:
            type: string
            length: '11'
            nullable: true
            gedmo:
                - versioned
        eissn:
            type: string
            length: '11'
            nullable: true
            gedmo:
                - versioned
        firstPublishDate:
            type: datetime
            column: first_publish_date
            nullable: true
        period:
            type: string
            length: 255
            nullable: true
            gedmo:
                  - versioned
        url:
            type: string
            length: 255
            nullable: true
            gedmo:
                  - versioned
        address:
            type: string
            length: 255
            nullable: true
            gedmo:
                  - versioned
        phone:
            type: string
            length: 255
            nullable: true
            gedmo:
                  - versioned
        email:
            type: string
            length: 255
            nullable: true
            gedmo:
                  - versioned
        published:
            type: boolean
            column: published
            gedmo:
                - versioned
            nullable: true
            options:
                default: 0
        status:
            type: integer
            gedmo:
                - versioned
            nullable: true
            options:
                default: 0
        image:
            type: string
            length: 255
            column: image
            nullable: true
            gedmo:
                  - versioned
        header:
            type: string
            length: 255
            nullable: true
            gedmo:
                  - versioned
        mandatoryLangId:
            type: integer
            nullable: TRUE
            column: mandatory_lang_id
            gedmo:
              - versioned
        logo:
            type: string
            length: 255
            nullable: true
            gedmo:
                  - versioned
        languageCodeSet:
            languages_code_set:
            type: string
            length: 30
            nullable: true
            gedmo:
                  - versioned
        googleAnalyticsId:
            type: string
            length: 50
            nullable: true
            column: google_analytics_id
        slug:
            type: string
            length: 255
            unique: true
            gedmo:
                versioned : ~
                slug:
                    seperator: _
                    fields:
                      - id
        themeId:
            type: integer
            column: theme_id
            nullable: true
            options:
                default: 0
            gedmo:
                  - versioned
        designId:
            type: integer
            column: design_id
            nullable: true
            options:
                default: 0
            gedmo:
                  - versioned
        institutionId:
            type: integer
            column: institution_id
            nullable: true
            options:
                default: 0
            gedmo:
                  - versioned
        isConfigured:
            column: is_configured
            type: boolean
            options:
                default: 0
            nullable: TRUE
            gedmo:
                  - versioned
        created:
            type: datetime
            gedmo:
              timestampable:
                on: create
        updated:
            type: datetime
            gedmo:
              timestampable:
                on: update
            nullable: true
        deletedAt:
            type: date
            nullable: true
        createdBy:
           type: string
           gedmo:
             blameable:
               on: create
           nullable: true
        updatedBy:
           type: string
           gedmo:
             blameable:
               on: update
           nullable: true
        tags:
            type: string
            nullable: true
            gedmo:
                  - versioned
        setup_status:
            type: boolean
            nullable: true
        footer_text:
            type: text
            nullable: true
            gedmo:
                  - versioned
        view_count:
            type: integer
            nullable: true
            options:
                default: 0
        download_count:
            type: integer
            nullable: true
            options:
                default: 0
        printed:
            type: boolean
            nullable: true
            options:
                default: false
            gedmo:
                  - versioned
    gedmo:
        soft_deleteable:
          field_name: deletedAt
          time_aware: false
        loggable: true
    uniqueConstraints:
        slugx:
            columns: slug
    lifecycleCallbacks: {  }
