Ojs\JournalBundle\Entity\JournalSetting:
  type: entity
  table: journal_setting
  repositoryClass: Ojs\JournalBundle\Entity\JournalSettingRepository
  cache:
    usage: NONSTRICT_READ_WRITE
  id:
    journal:
      associationKey: true
    setting:
      type: string
  fields:
    value:
      type: text
    createdBy:
       type: string
       gedmo:
         blameable:
           on: create
    updatedBy:
       type: string
       gedmo:
         blameable:
           on: update
  manyToOne:
    journal:
      targetEntity: Journal
      inversedBy: settings
  lifecycleCallbacks: {}

