Ojs\JournalBundle\Entity\JournalIndex:
  type: entity
  repositoryClass: Ojs\JournalBundle\Entity\JournalIndexRepository
  table: journal_indexs
  fields:
    name:
      type: string
      nullable: false
      length: 255
    logo:
      type: string 
      length: 255
      nullable: true
    logo_options:
      type: string
      nullable: true
    status:
      type: boolean
  id:
     id:
       generator:
         strategy: AUTO
       id: true
       type: integer
  oneToMany:
    journals_indexs:
      targetEntity: Ojs\JournalBundle\Entity\JournalsIndex
      mappedBy: journal_index
      cascade: ["all"]
      fetch: EXTRA_LAZY