Ojs\JournalBundle\Entity\Publisher:
    type: entity
    table: publisher
    repositoryClass: Ojs\JournalBundle\Entity\PublisherRepository
    cache:
        usage: NONSTRICT_READ_WRITE
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    oneToMany:
        journals:
            targetEntity: Journal
            mappedBy: publisher
            cascade: ["persist", "merge"]
            fetch: LAZY
        children:
            targetEntity: Publisher
            mappedBy: parent
            orderBy:
                  lft: ASC
            cache:
                  usage: NONSTRICT_READ_WRITE
        publisherThemes:
            targetEntity: Ojs\JournalBundle\Entity\PublisherTheme
            mappedBy: publisher
        publisherDesigns:
            targetEntity: Ojs\JournalBundle\Entity\PublisherDesign
            mappedBy: publisher
        publisherManagers:
            targetEntity: Ojs\AdminBundle\Entity\PublisherManagers
            mappedBy: publisher
    manyToOne:
        publisherType:
            targetEntity: Ojs\JournalBundle\Entity\PublisherTypes
            joinColumn:
                name: publisher_type_id
                referencedColumnName: id
            inversedBy: publishers
            cache:
                usage: NONSTRICT_READ_WRITE
        country:
            targetEntity: BulutYazilim\LocationBundle\Entity\Country
            joinColumn:
                  name: country_id
                  referencedColumnName: id
        parent:
              targetEntity: Publisher
              inversedBy: children
              joinColumn:
                    name: parent_id
                    referencedColumnName: id
                    onDelete: CASCADE
              gedmo:
                - treeParent
        theme:
          targetEntity: Ojs\JournalBundle\Entity\PublisherTheme
          joinColumn:
            name: theme_id
            referencedColumnName: id
          inversedBy: publishers
        design:
          targetEntity: Ojs\JournalBundle\Entity\PublisherDesign
          joinColumn:
            name: design_id
            referencedColumnName: id
          inversedBy: publishers
    fields:
        lft:
           type: integer
           gedmo:
             - treeLeft
        rgt:
           type: integer
           gedmo:
             - treeRight
        root:
           type: integer
           nullable: true
           gedmo:
             - treeRoot
        lvl:
           type: integer
           gedmo:
             - treeLevel
        name:
            type: string
            length: 255
            gedmo:
                - versioned
        slug:
            type: string
            length: 255
            unique: false
            gedmo:
                versioned : ~
                slug:
                    seperator: _
                    fields:
                      - name
        address:
            type: text
            nullable: TRUE
            gedmo:
                - versioned
        city:
            type: text
            nullable: true

        addressLat:
            type: string
            length: 255
            column: address_lat
            nullable: TRUE
            gedmo:
                  - versioned
        addressLong:
            type: string
            length: 255
            column: address_long
            nullable: TRUE
            gedmo:
                - versioned
        phone:
            type: string
            length: 255
            nullable: TRUE
            gedmo:
                - versioned
        fax:
            type: string
            length: 255
            nullable: TRUE
            gedmo:
                - versioned
        email:
            type: string
            length: 255
            nullable: TRUE
            gedmo:
                - versioned
        domain:
            type: string
            length: 255
            nullable: TRUE
            gedmo:
                - versioned
        url:
            type: string
            length: 255
            nullable: TRUE
            gedmo:
                - versioned
        wiki:
            type: string
            length: 255
            nullable: TRUE
            gedmo:
                  - versioned
        #IMAGES
        logo:
            type: string
            length: 255
            nullable: TRUE
            gedmo:
                - versioned
        header:
            type: string
            length: 255
            nullable: true
            gedmo:
                - versioned
        #IMAGES#
        created:
            type: datetime
            gedmo:
              timestampable:
                on: create
        updated:
            type: datetime
            gedmo:
              timestampable:
                on: update
        deletedAt:
            type: date
            nullable: true
        createdBy:
           type: string
           gedmo:
             blameable:
               on: create
           nullable: true
        updatedBy:
           type: string
           gedmo:
             blameable:
               on: update
           nullable: true
        tags:
            type: string
            nullable: true
            gedmo:
                  - versioned
        verified:
            type: boolean
            gedmo:
                  - versioned
        status:
            type: integer

    gedmo:
        soft_deleteable:
          field_name: deletedAt
          time_aware: false
        loggable: true
        tree:
             type: nested
    lifecycleCallbacks: {  }
