Ojs\JournalBundle\Entity\Subject:
    type: entity
    table: null
    repositoryClass: Ojs\JournalBundle\Entity\SubjectRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        lft:
            type: integer
            gedmo:
              - treeLeft
        rgt:
            type: integer
            gedmo:
              - treeRight
        root:
            type: integer
            nullable: true
            gedmo:
              - treeRoot
        lvl:
            type: integer
            gedmo:
              - treeLevel
        subject:
            type: string
            length: 255
            gedmo:
                - translatable
                - versioned
        slug:
            type: string
            length: 255
            gedmo:
                slug:
                    seperator: _
                    fields:
                      - subject
        description:
            type: text
            nullable: TRUE
            gedmo:
                - translatable
        totalJournalCount:
            column: total_journal_count
            nullable: TRUE
            options:
                default: 0
            type: integer
        created:
            type: datetime
            nullable: true
            gedmo:
              timestampable:
                on: create
        updated:
            type: datetime
            gedmo:
              timestampable:
                on: update
        deletedAt:
            type: date
            nullable: true
        createdBy:
           type: string
           gedmo:
             blameable:
               on: create
        updatedBy:
           type: string
           gedmo:
             blameable:
               on: update
        tags:
            type: string
            nullable: true
    manyToMany:
        users:
            targetEntity: Ojs\UserBundle\Entity\User
            cascade: {  }
            mappedBy: subjects
            inversedBy: null
            joinTable: {  }
            orderBy: null
        journals:
            targetEntity: Ojs\JournalBundle\Entity\Journal
            cascade: {  }
            mappedBy: subjects
            inversedBy: null
            joinTable: {  }
            orderBy: null
    gedmo:
        soft_deleteable:
          field_name: deletedAt
          time_aware: false
        loggable: true
        tree:
             type: nested
    lifecycleCallbacks: {  }
    manyToOne:
        parent:
          targetEntity: Subject
          inversedBy: children
          joinColumn:
            name: parent_id
            referencedColumnName: id
            onDelete: CASCADE
          gedmo:
            - treeParent
            
    oneToMany:
        children:
          targetEntity: Subject
          mappedBy: parent
          orderBy:
            lft: ASC
     
