Ojs\JournalBundle\Entity\SubmissionChecklist:
  type: entity
  repositoryClass: Ojs\JournalBundle\Entity\SubmissionChecklistRepository
  table: submission_checklist
  id:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO
  fields:
    label:
      type: string
    detail:
      type: text
      nullable: true
    journal_id:
      type: integer
    visible:
      type: boolean
      nullable: true
    locale:
      type: string
      nullable: true
    deletedAt:
      type: datetime
      nullable: true
  manyToOne:
    journal:
      targetEntity: Ojs\JournalBundle\Entity\Journal
      joinColumn:
        referencedColumnName: id
        name: journal_id
      inversedBy: submissionChecklist
  gedmo:
    soft_deleteable:
      field_name: deletedAt