ojs_journal_submission_me:
    path:     /{journalId}/submission/me
    defaults: { _controller: "OjsJournalBundle:ArticleSubmission:index" }

ojs_journal_submission_all:
    path:     /{journalId}/submission/all
    defaults: { _controller: "OjsJournalBundle:ArticleSubmission:index", all: true }

ojs_journal_submission_start:
  path:     /{journalId}/submission/start
  defaults: { _controller: "OjsJournalBundle:ArticleSubmission:start" }

ojs_journal_submission_new:
  path:     /{journalId}/submission/new
  defaults: { _controller: "OjsJournalBundle:ArticleSubmission:new" }

ojs_journal_submission_edit:
  path:     /{journalId}/submission/edit/{id}
  defaults: { _controller: "OjsJournalBundle:ArticleSubmission:edit" }

ojs_journal_submission_preview:
  path:     /{journalId}/submission/preview/{articleId}
  defaults: { _controller: "OjsJournalBundle:ArticleSubmission:preview" }

ojs_journal_submission_orcid:
  path:     /{journalId}/submission/orcid
  defaults: { _controller: "OjsJournalBundle:ArticleSubmission:getOrcidAuthor" }

ojs_journal_submission_cancel:
    path:     /{journalId}/submission/cancel/{id}
    defaults: { _controller: "OjsJournalBundle:ArticleSubmission:cancel"}

