ojs_journal_article_author_index:
    path:     /{journalId}/article/{articleId}/author
    defaults: { _controller: "OjsJournalBundle:ArticleAuthor:index" }

ojs_journal_article_author_show:
    path:     /{journalId}/article/{articleId}/author/{id}/show
    defaults: { _controller: "OjsJournalBundle:ArticleAuthor:show" }

ojs_journal_article_author_new:
    path:     /{journalId}/article/{articleId}/author/new
    defaults: { _controller: "OjsJournalBundle:ArticleAuthor:new" }

ojs_journal_article_author_create:
    path:     /{journalId}/article/{articleId}/author/create/
    defaults: { _controller: "OjsJournalBundle:ArticleAuthor:create" }
    methods: [POST]

ojs_journal_article_author_edit:
    path:     /{journalId}/article/{articleId}/author/{id}/edit
    defaults: { _controller: "OjsJournalBundle:ArticleAuthor:edit" }

ojs_journal_article_author_update:
    path:     /{journalId}/article/{articleId}/author/{id}/update
    defaults: { _controller: "OjsJournalBundle:ArticleAuthor:update" }
    methods:  [PUT]

ojs_journal_article_author_delete:
    path:     /{journalId}/article/{articleId}/author/{id}/delete
    defaults: { _controller: "OjsJournalBundle:ArticleAuthor:delete" }
    methods:  [DELETE]
