ojs_journal_board_index:
    path:     /{journalId}/board/
    defaults: { _controller: "OjsJournalBundle:Board:index" }

ojs_journal_board_sort:
    path:     /{journalId}/board/sort
    defaults: { _controller: "OjsJournalBundle:Board:sort" }

ojs_journal_board_show:
    path:     /{journalId}/board/{id}/show
    defaults: { _controller: "OjsJournalBundle:Board:show" }

ojs_journal_board_new:
    path:     /{journalId}/board/new
    defaults: { _controller: "OjsJournalBundle:Board:new" }

ojs_journal_board_create:
    path:     /{journalId}/board/create
    defaults: { _controller: "OjsJournalBundle:Board:create" }
    methods:  POST

ojs_journal_board_edit:
    path:     /{journalId}/board/{id}/edit
    defaults: { _controller: "OjsJournalBundle:Board:edit" }

ojs_journal_board_update:
    path:     /{journalId}/board/{id}/update
    defaults: { _controller: "OjsJournalBundle:Board:update" }
    methods: [PUT]

ojs_journal_board_member_sort:
    path:     /{journalId}/board/{boardId}/member/sort
    defaults: { _controller: "OjsJournalBundle:Board:memberSort" }

ojs_journal_board_delete:
    path:     /{journalId}/board/{id}/delete
    defaults: { _controller: "OjsJournalBundle:Board:delete" }
    methods: [DELETE]

ojs_journal_board_member_add:
    path:  /{journalId}/board/{boardId}/member/add
    defaults: { _controller: "OjsJournalBundle:Board:addMember" }
    methods:  [POST, PUT]

ojs_journal_board_member_remove:
    path:  /{journalId}/board/{boardId}/member/{id}/remove
    defaults: { _controller: "OjsJournalBundle:Board:removeMember" }

ojs_journal_board_oto_generate:
    path:  /{journalId}/board/oto-generate
    defaults: { _controller: "OjsJournalBundle:Board:otoGenerate" }