ojs_journal_checklist_index:
    path:     /{journalId}/checklist/
    defaults: { _controller: "OjsJournalBundle:SubmissionChecklist:index" }

ojs_journal_checklist_sort:
    path:     /{journalId}/checklist/sort
    defaults: { _controller: "OjsJournalBundle:SubmissionChecklist:sort" }

ojs_journal_checklist_show:
    path:     /{journalId}/checklist/{id}/show
    defaults: { _controller: "OjsJournalBundle:SubmissionChecklist:show" }

ojs_journal_checklist_new:
    path:     /{journalId}/checklist/new
    defaults: { _controller: "OjsJournalBundle:SubmissionChecklist:new" }

ojs_journal_checklist_create:
    path:     /{journalId}/checklist/create
    defaults: { _controller: "OjsJournalBundle:SubmissionChecklist:create" }
    methods:  POST

ojs_journal_checklist_edit:
    path:     /{journalId}/checklist/{id}/edit
    defaults: { _controller: "OjsJournalBundle:SubmissionChecklist:edit" }

ojs_journal_checklist_update:
    path:     /{journalId}/checklist/{id}/update
    defaults: { _controller: "OjsJournalBundle:SubmissionChecklist:update" }
    methods: [PUT]

ojs_journal_checklist_delete:
    path:     /{journalId}/checklist/{id}/delete
    defaults: { _controller: "OjsJournalBundle:SubmissionChecklist:delete" }
    methods: [DELETE]
