ojs_journal_page_index:
    path:     /{journalId}/page
    defaults: { _controller: "OjsJournalBundle:JournalPage:index" }

ojs_journal_page_sort:
    path:     /{journalId}/page/sort
    defaults: { _controller: "OjsJournalBundle:JournalPage:sort" }

ojs_journal_page_new:
    path:     /{journalId}/page/new
    defaults: { _controller: "OjsJournalBundle:JournalPage:new" }

ojs_journal_page_create:
    path:     /{journalId}/page/create
    defaults: { _controller: "OjsJournalBundle:JournalPage:create" }
    methods:  [POST]

ojs_journal_page_show:
    path:     /{journalId}/page/{id}/show
    defaults: { _controller: "OjsJournalBundle:JournalPage:show" }

ojs_journal_page_edit:
    path:     /{journalId}/page/{id}/edit
    defaults: { _controller: "OjsJournalBundle:JournalPage:edit" }

ojs_journal_page_update:
    path:     /{journalId}/page/{id}/update
    defaults: { _controller: "OjsJournalBundle:JournalPage:update" }
    methods:  [PUT]

ojs_journal_page_delete:
    path:     /{journalId}/page/{id}/delete
    defaults: { _controller: "OjsJournalBundle:JournalPage:delete" }
    methods:  [DELETE]
