ojs_journal_post_index:
    path:     /{journalId}/post
    defaults: { _controller: "OjsJournalBundle:JournalPost:index" }

ojs_journal_post_new:
    path:     /{journalId}/post/new
    defaults: { _controller: "OjsJournalBundle:JournalPost:new" }

ojs_journal_post_create:
    path:     /{journalId}/post/create
    defaults: { _controller: "OjsJournalBundle:JournalPost:create" }
    methods:  [POST]

ojs_journal_post_show:
    path:     /{journalId}/post/{id}/show
    defaults: { _controller: "OjsJournalBundle:JournalPost:show" }

ojs_journal_post_edit:
    path:     /{journalId}/post/{id}/edit
    defaults: { _controller: "OjsJournalBundle:JournalPost:edit" }

ojs_journal_post_update:
    path:     /{journalId}/post/{id}/update
    defaults: { _controller: "OjsJournalBundle:JournalPost:update" }
    methods:  [PUT]

ojs_journal_post_delete:
    path:     /{journalId}/post/{id}/delete
    defaults: { _controller: "OjsJournalBundle:JournalPost:delete" }
    methods:  [DELETE]