ojs_journal_user_index:
    path:     /{journalId}/user
    defaults: { _controller: "OjsJournalBundle:JournalUser:index" }

ojs_journal_user_new:
    path:     /{journalId}/user/new
    defaults: { _controller: "OjsJournalBundle:JournalUser:newUser" }

ojs_journal_user_create:
    path:     /{journalId}/user/create
    defaults: { _controller: "OjsJournalBundle:JournalUser:createUser" }

ojs_journal_user_add:
    path:     /{journalId}/user/add
    defaults: { _controller: "OjsJournalBundle:JournalUser:addUser" }
    methods:  [GET, POST]

ojs_journal_user_edit:
    path:     /{journalId}/user/{id}/edit
    defaults: { _controller: "OjsJournalBundle:JournalUser:editUser" }

ojs_journal_user_update:
    path:     /{journalId}/user/{id}/update
    defaults: { _controller: "OjsJournalBundle:JournalUser:updateUser" }
    methods:  [PUT]

ojs_journal_user_delete:
    path:     /{journalId}/user/{id}/delete
    defaults: { _controller: "OjsJournalBundle:JournalUser:deleteUser" }
    methods:  [DELETE]

ojs_journal_user_register_list:
    path:  /join
    defaults: { _controller: "OjsJournalBundle:JournalUser:registerAsAuthor" }

ojs_journal_user_register:
    path:  /join/{journalId}
    defaults: { _controller: "OjsJournalBundle:JournalUser:registerAsAuthor" }

ojs_journal_user_my:
    path:  /my
    defaults: { _controller: "OjsJournalBundle:JournalUser:journals" }

ojs_journal_user_leave:
    path: /leave/{journalId}
    defaults: { _controller: "OjsJournalBundle:JournalUser:leaveJournal" }

ojs_journal_user_leave_role:
    path: /leave/{journalId}/role/{roleId}
    defaults: { _controller: "OjsJournalBundle:JournalUser:leaveJournal" }

ojs_journal_user_search:
    path: /user/search
    defaults: { _controller: "OjsJournalBundle:JournalUser:getUserByUsername" }

ojs_journal_user_search_based_journal:
    path: /{journalId}/user/search
    defaults: { _controller: "OjsJournalBundle:JournalUser:getUserBasedJournal" }