ojs_admin_article_type_index:
    path:  /
    defaults: { _controller: "OjsAdminBundle:AdminArticleType:index" }

ojs_admin_article_type_show:
    path:  /{id}/show
    defaults: { _controller: "OjsAdminBundle:AdminArticleType:show" }

ojs_admin_article_type_new:
    path:  /new
    defaults: { _controller: "OjsAdminBundle:AdminArticleType:new" }

ojs_admin_article_type_create:
    path:  /create
    defaults: { _controller: "OjsAdminBundle:AdminArticleType:create" }
    methods: [POST]

ojs_admin_article_type_edit:
    path:  /{id}/edit
    defaults: { _controller: "OjsAdminBundle:AdminArticleType:edit" }

ojs_admin_article_type_update:
    path:  /{id}/update
    defaults: { _controller: "OjsAdminBundle:AdminArticleType:update" }
    methods:  [PUT]

ojs_admin_article_type_delete:
    path:  /{id}/delete
    defaults: { _controller: "OjsAdminBundle:AdminArticleType:delete" }
    methods:  [DELETE]
