ojs_admin_subject_index:
    path:  /
    defaults: { _controller: "OjsAdminBundle:AdminSubject:index" }

ojs_admin_subject_show:
    path:  /{id}/show
    defaults: { _controller: "OjsAdminBundle:AdminSubject:show" }

ojs_admin_subject_new:
    path:  /new
    defaults: { _controller: "OjsAdminBundle:AdminSubject:new" }

ojs_admin_subject_create:
    path:  /create
    defaults: { _controller: "OjsAdminBundle:AdminSubject:create" }
    methods: [POST]

ojs_admin_subject_edit:
    path:  /{id}/edit
    defaults: { _controller: "OjsAdminBundle:AdminSubject:edit" }

ojs_admin_subject_update:
    path:  /{id}/update
    defaults: { _controller: "OjsAdminBundle:AdminSubject:update" }
    methods:  [PUT]

ojs_admin_subject_delete:
    path:  /{id}/delete
    defaults: { _controller: "OjsAdminBundle:AdminSubject:delete" }
    methods:  [DELETE]
