ojs_admin_system_setting_index:
    path:     /
    defaults: { _controller: "OjsAdminBundle:AdminSystemSettings:index" }

ojs_admin_system_setting_update:
    path:     /update
    defaults: { _controller: "OjsAdminBundle:AdminSystemSettings:update" }
