ojs_admin_user_index:
    path:     /
    defaults: { _controller: "OjsAdminBundle:AdminUser:index" }

ojs_admin_user_show:
    path:  /{id}/show
    defaults: { _controller: "OjsAdminBundle:AdminUser:show" }

ojs_admin_user_new:
    path:  /new
    defaults: { _controller: "OjsAdminBundle:AdminUser:new" }

ojs_admin_user_create:
    path:  /create
    defaults: { _controller: "OjsAdminBundle:AdminUser:create" }

ojs_admin_user_edit:
    path:  /{id}/edit
    defaults: { _controller: "OjsAdminBundle:AdminUser:edit" }

ojs_admin_user_update:
    path:  /{id}/update
    defaults: { _controller: "OjsAdminBundle:AdminUser:update" }
    methods:  [PUT]

ojs_admin_user_block:
    path: /{id}/block
    defaults: { _controller: "OjsAdminBundle:AdminUser:block" }

ojs_admin_user_unblock:
    path: /{id}/unblock
    defaults: { _controller: "OjsAdminBundle:AdminUser:unblock" }

ojs_admin_user_password:
    path:  /{id}/password
    defaults: { _controller: "OjsAdminBundle:AdminUser:changePassword" }

ojs_admin_user_merge:
    path:  /merge
    defaults: { _controller: "OjsAdminBundle:AdminUser:merge" }
