ojs_application:
    resource: "@OjsSiteBundle/Resources/config/routing/application.yml"
    prefix: /apply
ojs_explore:
    resource: "@OjsSiteBundle/Resources/config/routing/explore.yml"
    prefix: /explore
redirect:
    path: /redirect/{type}/{id}
    defaults: { _controller: OjsSiteBundle:Redirect:redirect }

ojs_user_profile:
    path: /@{slug}
    defaults: { _controller: OjsSiteBundle:User:profile }

ojs_user_edit_profile:
    path: /user/update
    defaults: { _controller: "OjsSiteBundle:User:editProfile"}

ojs_user_custom_field:
    path: /user/custom_field
    defaults: { _controller: "OjsSiteBundle:User:customField"}

ojs_user_custom_field_create:
    path: /user/custom_field/create/{id}
    defaults: { _controller: "OjsSiteBundle:User:createCustomField", id: null}

ojs_user_custom_field_delete:
    path: /user/custom_field/delete/{id}
    defaults: { _controller: "OjsSiteBundle:User:deleteCustomField"}

ojs_user_connected_account:
    path: /user/connected_accounts
    defaults: { _controller: "OjsSiteBundle:User:connectedAccount" }

ojs_user_connected_account_add:
    path: /user/connected_accounts/add
    defaults: { _controller: "OjsSiteBundle:User:addConnectedAccount"}

ojs_user_connected_account_delete:
    path: /user/connected_accounts/delete/{id}
    defaults: { _controller: "OjsSiteBundle:User:deleteConnectedAccount"}

ojs_user_add_orcid_account:
    path: /user/connected_accounts/add/orcid
    defaults: { _controller: "OjsSiteBundle:User:addOrcidAccount" }

ojs_public_index:
    path:  /
    host: %base_host%
    defaults: { _controller: OjsSiteBundle:Site:index }

ojs_institutions_index:
    path:  /institutions
    defaults: { _controller: OjsSiteBundle:Site:institutionsIndex }

ojs_block:
    prefix: /block
    resource: "@OjsSiteBundle/Resources/config/routing/block.yml"

ojs_sitemap:
    prefix: /sitemap
    resource: "@OjsSiteBundle/Resources/config/routing/sitemap.yml"

ojs_search:
    resource: "@OjsSiteBundle/Resources/config/routing/search.yml"

#institution subdomain
ojs_institution_page:
    path:  /
    host: "{slug}.%base_host%"
    defaults: { _controller: OjsSiteBundle:Site:institutionPage }

ojs_journal_index:
    path:  /{slug}
    host: "{institution}.%base_host%"
    defaults: { _controller: OjsSiteBundle:Site:journalIndex }

ojs_journal_index_search:
    path:  /{slug}/search
    host: "{institution}.%base_host%"
    defaults: { _controller: OjsSiteBundle:Search:inJournal }

ojs_journal_index_articles:
    path: /{slug}/articles
    host: "{institution}.%base_host%"
    defaults: { _controller: OjsSiteBundle:Site:journalArticles }

ojs_site_journal_page:
    path: /{journal_slug}/page/{slug}
    host: "{institution}.%base_host%"
    defaults: { _controller: OjsSiteBundle:Site:journalPageDetail }

ojs_site_journal_post:
    path: /{journal_slug}/post/{slug}
    host: "{institution}.%base_host%"
    defaults: { _controller: OjsSiteBundle:Site:journalPostDetail }

ojs_last_articles_index:
    path:  /{slug}/last
    host: "{institution}.%base_host%"
    defaults: { _controller: OjsSiteBundle:Site:lastArticlesIndex }

ojs_archive_index:
    path:  /{slug}/archive
    host: "{institution}.%base_host%"
    defaults: { _controller: OjsSiteBundle:Site:archiveIndex }

ojs_announcement_index:
    path:  /{slug}/announcements
    host: "{institution}.%base_host%"
    defaults: { _controller: OjsSiteBundle:Site:announcementIndex }

ojs_journal_subscribe:
    path:  /{slug}/subscribe
    host: "{institution}.%base_host%"
    defaults: { _controller: OjsSiteBundle:Site:subscribe }

ojs_issue_page:
    path: /{journal_slug}/issue/{id}
    host: "{institution}.%base_host%"
    defaults: { _controller: OjsSiteBundle:Site:issuePage}

ojs_article_page:
    path:  /{slug}/issue/{issue_id}/{article_id}
    host: "{institution}.%base_host%"
    defaults: { _controller: OjsSiteBundle:Article:articlePage, issue_id: null}

ojs_journal_contacts:
    path: /{slug}/contacts
    host: "{institution}.%base_host%"
    defaults: { _controller: OjsSiteBundle:Site:journalContacts }

ojs_people:
    resource: "@OjsSiteBundle/Resources/config/routing/people.yml"
    prefix: /people

tos:
    path: /tos
    defaults: { _controller: OjsSiteBundle:Site:staticPages, page: 'tos' }

about:
    path: /about
    defaults: { _controller: OjsSiteBundle:Site:staticPages, page: 'about' }

wiki:
    path: /wiki
    defaults: { _controller: OjsSiteBundle:Site:staticPages, page: 'wiki' }

faq:
    path: /faq
    defaults: { _controller: OjsSiteBundle:Site:staticPages, page: 'faq' }

support:
    path: /support
    defaults: { _controller: OjsSiteBundle:Site:staticPages, page: 'support' }

privacy:
    path: /privacy
    defaults: { _controller: OjsSiteBundle:Site:staticPages, page: 'privacy'}

ojs_site_download:
    prefix:   /download
    resource: '@OjsSiteBundle/Resources/config/routing/download.yml'

ojs_site_page:
    path: /page/{slug}
    defaults: { _controller: OjsSiteBundle:Site:pageDetail }

ojs_site_post:
    path: /post/{slug}
    defaults: { _controller: OjsSiteBundle:Site:postDetail }
