Ojs\JournalBundle\Entity\JournalTranslation:
  properties:
    title:
      - NotBlank: ~

Ojs\JournalBundle\Entity\Journal:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: ['issn']
            message: 'issn.in.use'
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: ['eissn']
            message: 'eissn.in.use'
    properties:
        translations:
            - Valid: ~
        mandatoryLang:
            - NotBlank: {groups: [adminJournalEdit]}
        languages:
            - NotBlank: {groups: [adminJournalEdit]}
        issn:
            - Issn: ~
        eissn:
            - Issn: ~
        founded:
            - NotBlank: ~
            - GreaterThan:
                value: -116 years
