assetic:
  node: node
  debug: '%kernel.debug%'
  use_controller: false
  filters:
    cssrewrite: null
    uglifyjs:
      bin: '%kernel.root_dir%/Resources/node_modules/uglify-js/bin/uglifyjs'
    uglifycss:
      bin: '%kernel.root_dir%/Resources/node_modules/uglifycss/uglifycss'
  assets:
    stats_js:
      inputs:
        - '%kernel.root_dir%/../web/vendor/c3/c3.min.js'
        - '%kernel.root_dir%/../web/vendor/d3/d3.min.js'
    stats_css:
      inputs:
        - '%kernel.root_dir%/../web/vendor/c3/c3.min.css'
    main_js:
      inputs:
        - '%kernel.root_dir%/../web/vendor/jquery/jquery.min.js'
        - '%kernel.root_dir%/../web/vendor/bootstrap/dist/js/bootstrap.min.js'
        - '%kernel.root_dir%/../web/vendor/bootstrap-treeview/dist/bootstrap-treeview.min.js'
        - '%kernel.root_dir%/../web/vendor/trianglify/dist/trianglify.min.js'
        - '%kernel.root_dir%/../web/assets/app/js/common.js'
        - '%kernel.root_dir%/../web/vendor/moment/min/moment-with-locales.min.js'
        - '%kernel.root_dir%/../web/vendor/livestamp/livestamp.min.js'
        - '%kernel.root_dir%/../web/assets/app/js/plugins/analytics/analytics.js'
        - '%kernel.root_dir%/../web/vendor/summernote/dist/summernote.min.js'
        - '%kernel.root_dir%/../web/vendor/jQuery-Validation-Engine/js/languages/jquery.validationEngine-en.js'
        - '%kernel.root_dir%/../web/vendor/jQuery-Validation-Engine/js/jquery.validationEngine.js'
        - '%kernel.root_dir%/../web/assets/app/js/plugins/inputmask/jquery.inputmask.bundle.js'
        - '%kernel.root_dir%/../web/vendor/jquery-locationpicker-plugin/dist/locationpicker.jquery.min.js'
        - '%kernel.root_dir%/../web/vendor/select2/dist/js/select2.full.min.js'
        - '%kernel.root_dir%/../web/vendor/sweetalert/dist/sweetalert.min.js'
        - '%kernel.root_dir%/../web/vendor/fancybox/source/jquery.fancybox.pack.js'
        - '%kernel.root_dir%/../web/assets/app/js/plugins/highlight/highlight.js'
        - '%kernel.root_dir%/../web/vendor/list.js/dist/list.min.js'
        - '%kernel.root_dir%/../web/vendor/downloadjs/download.min.js'
        - '@BulutYazilimFeedbackBundle/Resources/public/js/feedback.js'
        - '@BulutYazilimFeedbackBundle/Resources/public/js/html2canvas.min.js'
        - '@BulutYazilimFeedbackBundle/Resources/public/js/admin.js'
        - '@BulutYazilimLocationBundle/Resources/public/js/location.js'
        - '@OjsSiteBundle/Resources/public/js/block.js'
        - '@A2lixTranslationFormBundle/Resources/public/js/a2lix_translation_bootstrap.js'
        - '@TetranzSelect2EntityBundle/Resources/public/js/select2entity.js'
        - '@OjsAdminBundle/Resources/public/js/dashboard.js'
    admin_main_css:
      inputs:
        - '%kernel.root_dir%/../web/vendor/bootstrap/dist/css/bootstrap.min.css'
        - '%kernel.root_dir%/../web/vendor/font-awesome/css/font-awesome.min.css'
        - '%kernel.root_dir%/../web/assets/app/css/app.css'
        - '%kernel.root_dir%/../web/vendor/select2/dist/css/select2.min.css'
        - '%kernel.root_dir%/../web/assets/app/css/admin.css'
        - '%kernel.root_dir%/../web/vendor/jQuery-Validation-Engine/css/validationEngine.jquery.css'
        - '%kernel.root_dir%/../web/vendor/summernote/dist/summernote.css'
        - '%kernel.root_dir%/../web/assets/app/css/_history.css'
        - '@BulutYazilimFeedbackBundle/Resources/public/css/feedback.css'
        - '%kernel.root_dir%/../web/vendor/sweetalert/dist/sweetalert.css'
        - '%kernel.root_dir%/../web/vendor/fancybox/source/jquery.fancybox.css'
    advanced_search_js:
      inputs: ['@OjsCoreBundle/Resources/public/js/search.js']
    submission_js:
      inputs:
        - '%kernel.root_dir%/../web/vendor/jquery-file-upload/js/vendor/jquery.ui.widget.js'
        - '%kernel.root_dir%/../web/vendor/jquery-file-upload/js/jquery.iframe-transport.js'
        - '%kernel.root_dir%/../web/vendor/jquery-file-upload/js/jquery.fileupload.js'
    submission_css:
      inputs:
        - '%kernel.root_dir%/../web/vendor/jquery-file-upload/css/jquery.fileupload.css'
        - '%kernel.root_dir%/../web/vendor/jquery-file-upload/css/jquery.fileupload-ui.css'
    jqueryui_js:
      inputs: ['%kernel.root_dir%/../web/assets/app/js/plugins/jqueryui/jquery-ui.min.js']
    jqueryui_css:
      input: ['%kernel.root_dir%/../web/assets/app/css/plugins/jqueryui/jquery-ui.min.css']
    site_css:
      input: ['@OjsSiteBundle/Resources/public/css/main.css']
    timeline_css:
      input: ['@OjsSiteBundle/Resources/public/css/timeline.css']
    hovercard_js:
      inputs:
        - '%kernel.root_dir%/../web/assets/app/js/plugins/hovercard/hovercard.min.js'
    formbuilder_js:
      inputs:
        - '%kernel.root_dir%/../web/vendor/formbuilder/vendor/js/vendor.js'
        - '%kernel.root_dir%/../web/vendor/formbuilder/dist/formbuilder.js'
    ace_js:
      inputs:
        - '%kernel.root_dir%/../web/vendor/ace-builds/src-min-noconflict/ace.js'
    bxslider_js:
      inputs:
        - '%kernel.root_dir%/../web/vendor/bxslider-4/dist/vendor/jquery.easing.1.3.js'
        - '%kernel.root_dir%/../web/vendor/bxslider-4/dist/vendor/jquery.fitvids.js'
        - '%kernel.root_dir%/../web/vendor/bxslider-4/dist/jquery.bxslider.min.js'
    bxslider_css:
      inputs:
        - '%kernel.root_dir%/../web/vendor/bxslider-4/dist/jquery.bxslider.min.css'
braincrafted_bootstrap:
  auto_configure:
    assetic: false
