app_extra:
  resource: .
  type: advanced_extra

journal_publisher_hosting:
  prefix: /
  resource: '@OjsSiteBundle/Resources/config/routing/hosting.yml'
  condition: 'not (context.getHost() matches "/%base_host%/")'

PrestaSitemapBundle:
    resource: "@PrestaSitemapBundle/Resources/config/routing.yml"
    prefix:   /

ojs_admin:
  resource: '@OjsAdminBundle/Resources/config/routing.yml'
  prefix: admin
  requirements:
    id: \d+

ojs_admin_root:
  resource: '@OjsAdminBundle/Resources/config/routing_root.yml'
  prefix:   /

ojs_oai:
  resource: '@OjsOAIBundle/Resources/config/routing.yml'
  prefix: /api/public/oai

ojs_journal:
  resource: '@OjsJournalBundle/Resources/config/routing.yml'
  prefix:   /

ojs_core:
  resource: '@OjsCoreBundle/Resources/config/routing.yml'
  prefix:   /

ojs_journal_panel:
  resource: '@OjsJournalBundle/Resources/config/routing_panel.yml'
  prefix: /journal

auth:
  resource: '@OjsUserBundle/Resources/config/routing.yml'
  prefix:   /

ojs_user:
  resource: '@OjsUserBundle/Controller/'
  type: annotation

ojs_location:
  resource: '@BulutYazilimLocationBundle/Resources/config/routing.yml'
  prefix:   /

feedback:
  resource: '@BulutYazilimFeedbackBundle/Resources/config/routing.yml'
  prefix:   /

oneup_uploader:
  resource: .
  type: uploader

_liip_imagine:
  resource: '@LiipImagineBundle/Resources/config/routing.xml'
  prefix:   /

change_locale:
  path: '/locale/{code}'
  host: "%base_host%"
  defaults:
    _controller: 'OjsJournalBundle:Common:changeLocale'

fos_js_routing:
  resource: '@FOSJsRoutingBundle/Resources/config/routing/routing.xml'

jb_fileupload_crop:
  resource: '@JbFileUploaderBundle/Resources/config/routing.yml'

ojs_site:
  resource: '@OjsSiteBundle/Resources/config/routing.yml'
  prefix:   /

fos_user:
  resource: '@FOSUserBundle/Resources/config/routing/all.xml'

JMSTranslationBundle_ui:
  resource: "@JMSTranslationBundle/Controller/"
  type:     annotation
  prefix:   /_trans

rest:
  type: rest
  resource: routing_rest.yml
  prefix: /api/

gregwar_captcha_routing:
    resource: "@GregwarCaptchaBundle/Resources/config/routing/routing.yml"