Ojs\UserBundle\Entity\User:
  constraints:
    - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
        fields: usernameCanonical
        errorPath: username
        message: fos_user.username.already_used
        groups:
          - journal_user
          - Default
          - ojs_register
          - editProfile
    - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
        fields: emailCanonical
        errorPath: email
        message: fos_user.email.already_used
        groups:
          - journal_user
          - Default
          - ojs_register
          - editProfile
  properties:
    username:
      - NotBlank: { groups: [Default, ojs_register, editProfile, journal_user] }
    password:
      - NotBlank: { groups: [Default, editProfile, journal_user] }
      - Length: { min: 6, groups: [Default, editProfile] }
    plainPassword:
      - NotBlank: { groups: [ojs_register] }
      - Length: { min: 6, groups: [ojs_register] }
    email:
      - NotBlank: { groups: [Default, ojs_register, editProfile, journal_user] }
      - Email: { groups: [Default, ojs_register, editProfile, journal_user] }
      - Ojs\UserBundle\Validator\Constraints\UniqueMultipleEmails: { message: 'user.multiple_mail.invalid', groups: [ojs_register, journal_user] }
    firstName:
      - NotBlank: { groups: [Default, ojs_register, editProfile, journal_user] }
    lastName:
      - NotBlank: { groups: [Default, ojs_register, journal_user] }
