ojs_journal_manager_journal_contact:
    resource: "@OjsJournalBundle/Resources/config/routing/journalcontact.yml"
    prefix:   /manager/journalcontact
    
ojs_journal_manager_journal_licence:
    resource: "@OjsJournalBundle/Resources/config/routing/journallicence.yml"
    prefix:   /manager/journal_licence

ojs_journal_manager_journals_indexes:
    resource: "@OjsJournalBundle/Resources/config/routing/journalsindex.yml"
    prefix:   /manager/journal/settings/indexes 
    
ojs_journal_articlefile:
    resource: "@OjsJournalBundle/Resources/config/routing/articlefile.yml"
    prefix:   /articlefile

ojs_journal_mailtemplate:
    resource: "@OjsJournalBundle/Resources/config/routing/mailtemplate.yml"
    prefix:   /manager/mailtemplate
  
change_selected_journal:
    pattern:  /manager/journal/selected/{journal_id}
    defaults: { _controller: "OjsJournalBundle:Journal:changeSelected" }


article_preview:
    pattern:  /manager/article/{id}/preview
    defaults: { _controller: "OjsJournalBundle:Article:preview" }
    
    
ojs_article_submission:
    resource: "@OjsJournalBundle/Resources/config/routing/articlesubmission.yml"

ojs_admin_journal_setup:
    prefix:   /admin/journal/setup/
    resource: "@OjsJournalBundle/Resources/config/routing/admin/journalsetup.yml"

ojs_manager_journal_setup:
    prefix:   /manager/journal/setup
    resource: "@OjsJournalBundle/Resources/config/routing/manager/journalsetup.yml"

journal_apply:
    pattern:  /journal/apply
    defaults: { _controller: "OjsJournalBundle:Journal:apply" }
    
manager_journal_section:
    resource: "@OjsJournalBundle/Resources/config/routing/journalsection.yml"
    prefix:   /manager/journal/section
   