services:
  ojs.journal_service:
    class: Ojs\JournalBundle\Service\JournalService
    arguments:
      - "@doctrine.orm.entity_manager"
      - "@session"
      - "@router"
      - "@security.token_storage"
      - "@request_stack"
      - "%defaultPublisherSlug%"

  journal.orm_event_listener:
    class: Ojs\JournalBundle\Listeners\AclOrmListener
    arguments: ["@service_container"]
    tags:
        - { name: doctrine.event_listener, event: postPersist }

  form.type.journal_users_type:
    class: Ojs\JournalBundle\Form\Type\JournalUsersFieldType
    arguments: ["@ojs.journal_service"]
    tags:
        - { name: form.type, alias: journal_users_type }

  ojs.serializationlistener:
    class: Ojs\CoreBundle\Listeners\SerializationListener
    arguments: []
    tags:
        - { name: jms_serializer.event_subscriber }
  ojs.journal.subscription_subscriber:
    class: Ojs\JournalBundle\Listeners\SubscriptionSubscriber
    arguments: ["@doctrine.orm.entity_manager", "@ojs_mailer"]
    tags:
      - { name: kernel.event_subscriber }

  journal.event_listener:
    class: Ojs\JournalBundle\EventListener\JournalEventListener
    arguments: ["@router", "@doctrine.orm.entity_manager", "@ojs_mailer"]
    tags:
      - { name: kernel.event_subscriber }

  ojs.mail_listener.journal_item:
    class: Ojs\JournalBundle\Listeners\AbstractJournalItemMailer
    abstract: true
    arguments: ["@ojs_mailer", "@doctrine", "@security.token_storage"]
    tags:
      - { name: kernel.event_subscriber }

  ojs.mail_listener.article:
    class: Ojs\JournalBundle\Listeners\ArticleMailer
    parent: ojs.mail_listener.journal_item

  ojs.mail_listener.journal_announcement:
    class: Ojs\JournalBundle\Listeners\JournalAnnouncementMailer
    parent: ojs.mail_listener.journal_item

  ojs.mail_listener.journal_post:
    class: Ojs\JournalBundle\Listeners\JournalPostMailer
    parent: ojs.mail_listener.journal_item

  ojs.mail_listener.journal_page:
    class: Ojs\JournalBundle\Listeners\JournalPageMailer
    parent: ojs.mail_listener.journal_item

  ojs.mail_listener.issue:
    class: Ojs\JournalBundle\Listeners\IssueMailer
    parent: ojs.mail_listener.journal_item

  ojs.mail_listener.section:
    class: Ojs\JournalBundle\Listeners\SectionMailer
    parent: ojs.mail_listener.journal_item

  ojs.mail_listener.board:
    class: Ojs\JournalBundle\Listeners\BoardMailer
    parent: ojs.mail_listener.journal_item

  ojs.mail_listener.journal_contact:
    class: Ojs\JournalBundle\Listeners\JournalContactMailer
    parent: ojs.mail_listener.journal_item

  ojs.mail_listener.journal_index:
    class: Ojs\JournalBundle\Listeners\JournalIndexMailer
    parent: ojs.mail_listener.journal_item

#  journal.numerator_orm_subscriber:
#    class: Ojs\JournalBundle\Listeners\NumeratorOrmSubscriber
#    tags:
#        - { name: doctrine.event_listener, event: postPersist }
