admin_notification:
    path:     /
    defaults: { _controller: "OjsUserBundle:Notification:index" }

admin_notification_show:
    path:     /{id}/show
    defaults: { _controller: "OjsUserBundle:Notification:show" }

admin_notification_new:
    path:     /new
    defaults: { _controller: "OjsUserBundle:Notification:new" }

admin_notification_create:
    path:     /create
    defaults: { _controller: "OjsUserBundle:Notification:create" }
    requirements: { _method: post }

admin_notification_edit:
    path:     /{id}/edit
    defaults: { _controller: "OjsUserBundle:Notification:edit" }

admin_notification_update:
    path:     /{id}/update
    defaults: { _controller: "OjsUserBundle:Notification:update" }
    requirements: { _method: post|put }

admin_notification_delete:
    path:     /{id}/delete
    defaults: { _controller: "OjsUserBundle:Notification:delete" }
