api_contact_types:
  type:         rest
  resource:     "@OjsApiBundle/Controller/Admin/ContactTypesRestController.php"
  prefix:       /v1
  name_prefix:  api_1_

api_journal:
  type:         rest
  resource:     "@OjsApiBundle/Controller/Admin/JournalRestController.php"
  prefix:       /v1
  name_prefix:  api_1_

api_publisher:
  type:         rest
  resource:     "@OjsApiBundle/Controller/Admin/PublisherRestController.php"
  prefix:       /v1
  name_prefix:  api_1_

api_institution:
  type:         rest
  resource:     "@OjsApiBundle/Controller/Admin/InstitutionRestController.php"
  prefix:       /v1
  name_prefix:  api_1_

api_subject:
  type:         rest
  resource:     "@OjsApiBundle/Controller/Admin/SubjectRestController.php"
  prefix:       /v1
  name_prefix:  api_1_

api_user:
  type:         rest
  resource:     "@OjsApiBundle/Controller/Admin/UserRestController.php"
  prefix:       /v1
  name_prefix:  api_1_

api_lang:
  type:         rest
  resource:     "@OjsApiBundle/Controller/Admin/LangRestController.php"
  prefix:       /v1
  name_prefix:  api_1_

api_index:
  type:         rest
  resource:     "@OjsApiBundle/Controller/Admin/IndexRestController.php"
  prefix:       /v1
  name_prefix:  api_1_

api_period:
  type:         rest
  resource:     "@OjsApiBundle/Controller/Admin/PeriodRestController.php"
  prefix:       /v1
  name_prefix:  api_1_

api_person_title:
  type:         rest
  resource:     "@OjsApiBundle/Controller/Admin/PersonTitleRestController.php"
  prefix:       /v1
  name_prefix:  api_1_

api_publisher_type:
  type:         rest
  resource:     "@OjsApiBundle/Controller/Admin/PublisherTypeRestController.php"
  prefix:       /v1
  name_prefix:  api_1_

api_article_type:
  type:         rest
  resource:     "@OjsApiBundle/Controller/Admin/ArticleTypeRestController.php"
  prefix:       /v1
  name_prefix:  api_1_

api_contact:
  type:         rest
  resource:     "@OjsApiBundle/Controller/Admin/ContactRestController.php"
  prefix:       /v1
  name_prefix:  api_1_

api_contact_type:
  type:         rest
  resource:     "@OjsApiBundle/Controller/Admin/ContactTypesRestController.php"
  prefix:       /v1
  name_prefix:  api_1_

api_post:
  type:         rest
  resource:     "@OjsApiBundle/Controller/Admin/PostRestController.php"
  prefix:       /v1
  name_prefix:  api_1_

api_page:
  type:         rest
  resource:     "@OjsApiBundle/Controller/Admin/PageRestController.php"
  prefix:       /v1
  name_prefix:  api_1_

api_announcement:
  type:         rest
  resource:     "@OjsApiBundle/Controller/Admin/AnnouncementRestController.php"
  prefix:       /v1
  name_prefix:  api_1_

api_publisher_theme:
  type:         rest
  resource:     "@OjsApiBundle/Controller/Admin/PublisherThemeRestController.php"
  prefix:       /v1
  name_prefix:  api_1_

api_publisher_manager:
  type:         rest
  resource:     "@OjsApiBundle/Controller/Admin/PublisherManagerRestController.php"
  prefix:       /v1
  name_prefix:  api_1_

api_journal_issue:
  type:         rest
  resource:     "@OjsApiBundle/Controller/Journal/JournalIssueRestController.php"
  prefix:       /v1/journal/{journalId}
  name_prefix:  api_1_
  requirements:
      journalId:  \d+

api_journal_theme:
  type:         rest
  resource:     "@OjsApiBundle/Controller/Journal/JournalThemeRestController.php"
  prefix:       /v1/journal/{journalId}
  name_prefix:  api_1_
  requirements:
      journalId:  \d+

api_journal_board:
  type:         rest
  resource:     "@OjsApiBundle/Controller/Journal/JournalBoardRestController.php"
  prefix:       /v1/journal/{journalId}
  name_prefix:  api_1_
  requirements:
      journalId:  \d+

api_journal_section:
  type:         rest
  resource:     "@OjsApiBundle/Controller/Journal/JournalSectionRestController.php"
  prefix:       /v1/journal/{journalId}
  name_prefix:  api_1_
  requirements:
      journalId:  \d+

api_journal_article:
  type:         rest
  resource:     "@OjsApiBundle/Controller/Journal/JournalArticleRestController.php"
  prefix:       /v1/journal/{journalId}
  name_prefix:  api_1_
  requirements:
      journalId:  \d+

api_analytics :
  type: rest
  resource:     "@OjsApiBundle/Controller/AnalyticsRestController.php"
  prefix:       /v1/
  name_prefix:  api_1_
  options:
      expose: true
  requirements:
        id:  \d+
