parameters:
    ojs_api.contact_type.handler.class: Ojs\ApiBundle\Handler\ContactTypesHandler
    ojs_api.contact_type.class: Ojs\JournalBundle\Entity\ContactTypes
    ojs_api.journal.handler.class: Ojs\ApiBundle\Handler\JournalHandler
    ojs_api.journal.class: Ojs\JournalBundle\Entity\Journal
    ojs_api.publisher.handler.class: Ojs\ApiBundle\Handler\PublisherHandler
    ojs_api.publisher.class: Ojs\JournalBundle\Entity\Publisher
    ojs_api.institution.handler.class: Ojs\ApiBundle\Handler\InstitutionHandler
    ojs_api.institution.class: Ojs\JournalBundle\Entity\Institution
    ojs_api.subject.handler.class: Ojs\ApiBundle\Handler\SubjectHandler
    ojs_api.subject.class: Ojs\JournalBundle\Entity\Subject
    ojs_api.user.handler.class: Ojs\ApiBundle\Handler\UserHandler
    ojs_api.user.class: Ojs\UserBundle\Entity\User
    ojs_api.lang.handler.class: Ojs\ApiBundle\Handler\LangHandler
    ojs_api.lang.class: Ojs\JournalBundle\Entity\Lang
    ojs_api.index.handler.class: Ojs\ApiBundle\Handler\IndexHandler
    ojs_api.index.class: Ojs\JournalBundle\Entity\Index
    ojs_api.period.handler.class: Ojs\ApiBundle\Handler\PeriodHandler
    ojs_api.period.class: Ojs\JournalBundle\Entity\Period
    ojs_api.person_title.handler.class: Ojs\ApiBundle\Handler\PersonTitleHandler
    ojs_api.person_title.class: Ojs\JournalBundle\Entity\PersonTitle
    ojs_api.publisher_type.handler.class: Ojs\ApiBundle\Handler\PublisherTypeHandler
    ojs_api.publisher_type.class: Ojs\JournalBundle\Entity\PublisherTypes
    ojs_api.article_type.handler.class: Ojs\ApiBundle\Handler\ArticleTypeHandler
    ojs_api.article_type.class: Ojs\JournalBundle\Entity\ArticleTypes
    ojs_api.contact.handler.class: Ojs\ApiBundle\Handler\ContactHandler
    ojs_api.contact.class: Ojs\JournalBundle\Entity\JournalContact
    ojs_api.post.handler.class: Ojs\ApiBundle\Handler\PostHandler
    ojs_api.post.class: Ojs\AdminBundle\Entity\AdminPost
    ojs_api.page.handler.class: Ojs\ApiBundle\Handler\PageHandler
    ojs_api.page.class: Ojs\AdminBundle\Entity\AdminPage
    ojs_api.announcement.handler.class: Ojs\ApiBundle\Handler\AnnouncementHandler
    ojs_api.announcement.class: Ojs\AdminBundle\Entity\AdminAnnouncement
    ojs_api.publisher_theme.handler.class: Ojs\ApiBundle\Handler\PublisherThemeHandler
    ojs_api.publisher_theme.class: Ojs\JournalBundle\Entity\PublisherTheme
    ojs_api.publisher_manager.handler.class: Ojs\ApiBundle\Handler\PublisherManagerHandler
    ojs_api.publisher_manager.class: Ojs\AdminBundle\Entity\PublisherManagers
    ojs_api.journal_issue.handler.class: Ojs\ApiBundle\Handler\JournalIssueHandler
    ojs_api.journal_issue.class: Ojs\JournalBundle\Entity\Issue
    ojs_api.journal_theme.handler.class: Ojs\ApiBundle\Handler\JournalThemeHandler
    ojs_api.journal_theme.class: Ojs\JournalBundle\Entity\JournalTheme
    ojs_api.journal_board.handler.class: Ojs\ApiBundle\Handler\JournalBoardHandler
    ojs_api.journal_board.class: Ojs\JournalBundle\Entity\Board
    ojs_api.journal_section.handler.class: Ojs\ApiBundle\Handler\JournalSectionHandler
    ojs_api.journal_section.class: Ojs\JournalBundle\Entity\Section
    ojs_api.journal_article.handler.class: Ojs\ApiBundle\Handler\JournalArticleHandler
    ojs_api.journal_article.class: Ojs\JournalBundle\Entity\Article

services:
    ojs_api.contact_type.handler:
        class: "%ojs_api.contact_type.handler.class%"
        arguments: ['@doctrine.orm.entity_manager', '%ojs_api.contact_type.class%', '@form.factory']
    ojs_api.journal.handler:
        class: "%ojs_api.journal.handler.class%"
        arguments: ['@doctrine.orm.entity_manager', '%ojs_api.journal.class%', '@form.factory', '@ojs_api_handler_helper']
    ojs_api.publisher.handler:
        class: "%ojs_api.publisher.handler.class%"
        arguments: ['@doctrine.orm.entity_manager', '%ojs_api.publisher.class%', '@form.factory']
    ojs_api.institution.handler:
        class: "%ojs_api.institution.handler.class%"
        arguments: ['@doctrine.orm.entity_manager', '%ojs_api.institution.class%', '@form.factory']
    ojs_api.subject.handler:
        class: "%ojs_api.subject.handler.class%"
        arguments: ['@doctrine.orm.entity_manager', '%ojs_api.subject.class%', '@form.factory']
    ojs_api.user.handler:
        class: "%ojs_api.user.handler.class%"
        arguments: ['@doctrine.orm.entity_manager', '%ojs_api.user.class%', '@form.factory']
    ojs_api.lang.handler:
        class: "%ojs_api.lang.handler.class%"
        arguments: ['@doctrine.orm.entity_manager', '%ojs_api.lang.class%', '@form.factory']
    ojs_api.index.handler:
        class: "%ojs_api.index.handler.class%"
        arguments: ['@doctrine.orm.entity_manager', '%ojs_api.index.class%', '@form.factory']
    ojs_api.period.handler:
        class: "%ojs_api.period.handler.class%"
        arguments: ['@doctrine.orm.entity_manager', '%ojs_api.period.class%', '@form.factory']
    ojs_api.person_title.handler:
        class: "%ojs_api.person_title.handler.class%"
        arguments: ['@doctrine.orm.entity_manager', '%ojs_api.person_title.class%', '@form.factory']
    ojs_api.publisher_type.handler:
        class: "%ojs_api.publisher_type.handler.class%"
        arguments: ['@doctrine.orm.entity_manager', '%ojs_api.publisher_type.class%', '@form.factory']
    ojs_api.article_type.handler:
        class: "%ojs_api.article_type.handler.class%"
        arguments: ['@doctrine.orm.entity_manager', '%ojs_api.article_type.class%', '@form.factory']
    ojs_api.contact.handler:
        class: "%ojs_api.contact.handler.class%"
        arguments: ['@doctrine.orm.entity_manager', '%ojs_api.contact.class%', '@form.factory']
    ojs_api.post.handler:
        class: "%ojs_api.post.handler.class%"
        arguments: ['@doctrine.orm.entity_manager', '%ojs_api.post.class%', '@form.factory']
    ojs_api.page.handler:
        class: "%ojs_api.page.handler.class%"
        arguments: ['@doctrine.orm.entity_manager', '%ojs_api.page.class%', '@form.factory']
    ojs_api.announcement.handler:
        class: "%ojs_api.announcement.handler.class%"
        arguments: ['@doctrine.orm.entity_manager', '%ojs_api.announcement.class%', '@form.factory']
    ojs_api.publisher_theme.handler:
        class: "%ojs_api.publisher_theme.handler.class%"
        arguments: ['@doctrine.orm.entity_manager', '%ojs_api.publisher_theme.class%', '@form.factory']
    ojs_api.publisher_manager.handler:
        class: "%ojs_api.publisher_manager.handler.class%"
        arguments: ['@doctrine.orm.entity_manager', '%ojs_api.publisher_manager.class%', '@form.factory']
    ojs_api.journal_issue.handler:
        class: "%ojs_api.journal_issue.handler.class%"
        arguments: ['@doctrine.orm.entity_manager', '%ojs_api.journal_issue.class%', '@form.factory', '@ojs.journal_service', '@kernel', '@ojs_api_handler_helper']
    ojs_api.journal_theme.handler:
        class: "%ojs_api.journal_theme.handler.class%"
        arguments: ['@doctrine.orm.entity_manager', '%ojs_api.journal_theme.class%', '@form.factory', '@ojs.journal_service']
    ojs_api.journal_board.handler:
        class: "%ojs_api.journal_board.handler.class%"
        arguments: ['@doctrine.orm.entity_manager', '%ojs_api.journal_board.class%', '@form.factory', '@ojs.journal_service']
    ojs_api.journal_section.handler:
        class: "%ojs_api.journal_section.handler.class%"
        arguments: ['@doctrine.orm.entity_manager', '%ojs_api.journal_section.class%', '@form.factory', '@ojs.journal_service']
    ojs_api.journal_article.handler:
        class: "%ojs_api.journal_article.handler.class%"
        arguments: ['@doctrine.orm.entity_manager', '%ojs_api.journal_article.class%', '@form.factory', '@ojs.journal_service', '@kernel', '@ojs_api_handler_helper']

    ojs_api.twig.api_extension:
        class: Ojs\ApiBundle\Service\Twig\ApiTwigExtension
        arguments:
            - "@router"
        tags:
            - { name: twig.extension }