journal_publisher_hosting:
    path:  /
    defaults: { _controller: "OjsSiteBundle:Hosting:index" }

journal_hosting_archive:
    path:  /archive
    defaults: { _controller: "OjsSiteBundle:Hosting:archiveIndex", isJournalHosting: true }

journal_hosting_last:
    path:  /last
    defaults: { _controller: "OjsSiteBundle:Hosting:last", isJournalHosting: true }

journal_hosting_contacts:
    path:  /contacts
    defaults: { _controller: "OjsSiteBundle:Hosting:contacts", isJournalHosting: true }

journal_hosting_board:
    path:  /board
    defaults: { _controller: "OjsSiteBundle:Hosting:board", isJournalHosting: true }

journal_hosting_announcement:
    path:  /announcements
    defaults: { _controller: "OjsSiteBundle:Hosting:announcement", isJournalHosting: true }

journal_hosting_page:
    path: /page/{slug}
    defaults: { _controller: "OjsSiteBundle:Hosting:page", [slug: null ,isJournalHosting: true] }

journal_hosting_issue:
    path: /issue/{id}
    defaults: { _controller: "OjsSiteBundle:Hosting:issuePage", [id: null, isJournalHosting: true]}

journal_hosting_issue_article:
    path:  /issue/{issue_id}/{article_id}
    defaults: { _controller: "OjsSiteBundle:Hosting:articlePage", [issue_id: null, isJournalHosting: true]}

