ojs_search_advanced:
    path: /search/advanced
    defaults: { _controller: "OjsSiteBundle:Search:advanced" }

ojs_search_index:
    path:     /search/{page}
    defaults: { _controller: "OjsSiteBundle:Search:index",page: 1 }

ojs_tags_cloud:
    path: /tags/cloud
    defaults: { _controller: "OjsSiteBundle:Search:tagCloud" }
