ojs_installer_homepage:
    path: /install
    defaults: { _controller: OjsInstallerBundle:Home:index }
ojs_installer_check:
    path: /install/check
    defaults: { _controller: OjsInstallerBundle:Check:check }
ojs_installer_configure:
    path: /install/configure
    defaults: { _controller: OjsInstallerBundle:Config:configure }
ojs_installer_save_configure:
    path: /install/saveconfiguration
    defaults: { _controller: OjsInstallerBundle:Config:save }
ojs_installer_setup:
    path: /install/setup
    defaults: { _controller: OjsInstallerBundle:Setup:setup }
ojs_installer_create_admin:
    path: /install/createadmin
    defaults: { _controller: OjsInstallerBundle:Setup:createUser }
ojs_installer_summary:
    path: /install/summary
    defaults: { _controller: OjsInstallerBundle:Summary:summary }

ojs_installer_update:
    path: /update
    defaults: { _controller: OjsInstallerBundle:Update:index }
ojs_installer_update_confirm:
    path: /update/confirm
    defaults: { _controller: OjsInstallerBundle:Update:update }