manager_journals_indexes:
    path:     /{journal}
    defaults: { _controller: "OjsJournalBundle:JournalsIndex:index", journal: 0 }
    requirements:
      journal: \d+

manager_journals_indexes_show:
    path:     /{id}/show
    defaults: { _controller: "OjsJournalBundle:JournalsIndex:show" }

manager_journals_indexes_new:
    path:     /new/{journal}
    defaults: { _controller: "OjsJournalBundle:JournalsIndex:new",journal: null }

manager_journals_indexes_create:
    path:     /create/{journal}
    defaults: { _controller: "OjsJournalBundle:JournalsIndex:create",journal: null }
    methods:  POST

manager_journals_indexes_edit:
    path:     /{id}/edit
    defaults: { _controller: "OjsJournalBundle:JournalsIndex:edit" }

manager_journals_indexes_update:
    path:     /{id}/update
    defaults: { _controller: "OjsJournalBundle:JournalsIndex:update" }
    methods:  [POST, PUT]

manager_journals_indexes_delete:
    path:     /{id}/delete
    defaults: { _controller: "OjsJournalBundle:JournalsIndex:delete" }
    methods:  [POST, DELETE]
