manager_submission_checklist:
    path:     /
    defaults: { _controller: "OjsJournalBundle:SubmissionChecklist:index" }

manager_submission_checklist_show:
    path:     /{id}/show
    defaults: { _controller: "OjsJournalBundle:SubmissionChecklist:show" }

manager_submission_checklist_new:
    path:     /new
    defaults: { _controller: "OjsJournalBundle:SubmissionChecklist:new" }

manager_submission_checklist_create:
    path:     /create
    defaults: { _controller: "OjsJournalBundle:SubmissionChecklist:create" }
    methods:  POST

manager_submission_checklist_edit:
    path:     /{id}/edit
    defaults: { _controller: "OjsJournalBundle:SubmissionChecklist:edit" }

manager_submission_checklist_update:
    path:     /{id}/update
    defaults: { _controller: "OjsJournalBundle:SubmissionChecklist:update" }
    methods:  [POST, PUT]

manager_submission_checklist_delete:
    path:     /{id}/delete
    defaults: { _controller: "OjsJournalBundle:SubmissionChecklist:delete" }
    methods:  [POST, DELETE]
