ojs_admin_dashboard:
    path:     dashboard
    defaults: { _controller: "OjsAdminBundle:Admin:dashboard" }

ojs_admin_stats:
    path:  stats
    defaults: { _controller: "OjsAdminBundle:Admin:stats" }

ojs_admin_user:
    resource: "@OjsAdminBundle/Resources/config/routing/user.yml"
    prefix:   user

ojs_admin_journal:
    resource: "@OjsAdminBundle/Resources/config/routing/journal.yml"
    prefix:   journal

ojs_admin_publisher:
    resource: "@OjsAdminBundle/Resources/config/routing/publisher.yml"
    prefix:   publisher

ojs_admin_institution:
    resource: "@OjsAdminBundle/Resources/config/routing/institution.yml"
    prefix:   institution

ojs_admin_mail_template:
    resource: "@OjsAdminBundle/Resources/config/routing/mail_template.yml"
    prefix:   mail-template

ojs_admin_publisher_type:
    resource: "@OjsAdminBundle/Resources/config/routing/publisher_type.yml"
    prefix:   publisher-type

ojs_admin_publisher_theme:
    resource: "@OjsAdminBundle/Resources/config/routing/publisher_theme.yml"
    prefix:   publisher-theme

ojs_admin_publisher_design:
    resource: "@OjsAdminBundle/Resources/config/routing/publisher_design.yml"
    prefix:   publisher-design

ojs_admin_publisher_manager:
    resource: "@OjsAdminBundle/Resources/config/routing/publisher_managers.yml"
    prefix:   publisher-manager


ojs_admin_journal_theme:
    resource: "@OjsAdminBundle/Resources/config/routing/admin_journal_theme.yml"
    prefix:   journal-theme

ojs_admin_subject:
    resource: "@OjsAdminBundle/Resources/config/routing/subject.yml"
    prefix:   subject

ojs_admin_contact_type:
    resource: "@OjsAdminBundle/Resources/config/routing/contact_type.yml"
    prefix:   contact-type

ojs_admin_language:
    resource: "@OjsAdminBundle/Resources/config/routing/language.yml"
    prefix:   language

ojs_admin_article_type:
    resource: "@OjsAdminBundle/Resources/config/routing/article_type.yml"
    prefix:   article-type

ojs_admin_application:
    resource: "@OjsAdminBundle/Resources/config/routing/journal_application.yml"
    prefix:   application

ojs_admin_publisher_application:
    resource: "@OjsAdminBundle/Resources/config/routing/publisher_application.yml"
    prefix:   application

ojs_admin_index:
    resource: "@OjsAdminBundle/Resources/config/routing/index.yml"
    prefix:   index

ojs_admin_application_file_application_file:
    resource: "@OjsAdminBundle/Resources/config/routing/application_file.yml"
    prefix:   journal-application-file

ojs_admin_system_settings:
    resource: "@OjsAdminBundle/Resources/config/routing/system_settings.yml"
    prefix:   settings

ojs_admin_announcement:
    resource: "@OjsAdminBundle/Resources/config/routing/announcement.yml"
    prefix:   announcement

ojs_admin_page:
    resource: "@OjsAdminBundle/Resources/config/routing/page.yml"
    prefix:   page

ojs_admin_post:
    resource: "@OjsAdminBundle/Resources/config/routing/post.yml"
    prefix:   post

ojs_admin_contact:
    resource: "@OjsAdminBundle/Resources/config/routing/contact.yml"
    prefix:   contact

ojs_admin_period:
    resource: "@OjsAdminBundle/Resources/config/routing/period.yml"
    prefix:   period

ojs_admin_person_title:
    resource: "@OjsAdminBundle/Resources/config/routing/person_title.yml"
    prefix:   person-title

ojs_admin_file:
    resource: "@OjsAdminBundle/Resources/config/routing/file.yml"
    prefix:   file
