ojs_admin_announcement_index:
    path:     /
    defaults: { _controller: "OjsAdminBundle:AdminAnnouncement:index" }

ojs_admin_announcement_new:
    path:     /new
    defaults: { _controller: "OjsAdminBundle:AdminAnnouncement:new" }

ojs_admin_announcement_create:
    path:     /create
    defaults: { _controller: "OjsAdminBundle:AdminAnnouncement:create" }
    methods:  [POST]

ojs_admin_announcement_show:
    path:     /{id}/show
    defaults: { _controller: "OjsAdminBundle:AdminAnnouncement:show" }

ojs_admin_announcement_edit:
    path:     /{id}/edit
    defaults: { _controller: "OjsAdminBundle:AdminAnnouncement:edit" }

ojs_admin_announcement_update:
    path:     /{id}/update
    defaults: { _controller: "OjsAdminBundle:AdminAnnouncement:update" }
    methods:  [PUT]

ojs_admin_announcement_delete:
    path:     /{id}/delete
    defaults: { _controller: "OjsAdminBundle:AdminAnnouncement:delete" }
    methods:  [DELETE]