ojs_admin_contact_type_index:
    path:  /
    defaults: { _controller: "OjsAdminBundle:AdminContactType:index" }

ojs_admin_contact_type_show:
    path:  /{id}/show
    defaults: { _controller: "OjsAdminBundle:AdminContactType:show" }

ojs_admin_contact_type_new:
    path:  /new
    defaults: { _controller: "OjsAdminBundle:AdminContactType:new" }

ojs_admin_contact_type_create:
    path:  /create
    defaults: { _controller: "OjsAdminBundle:AdminContactType:create" }
    methods: [POST]

ojs_admin_contact_type_edit:
    path:  /{id}/edit
    defaults: { _controller: "OjsAdminBundle:AdminContactType:edit" }

ojs_admin_contact_type_update:
    path:  /{id}/update
    defaults: { _controller: "OjsAdminBundle:AdminContactType:update" }
    methods:  [PUT]

ojs_admin_contact_type_delete:
    path:  /{id}/delete
    defaults: { _controller: "OjsAdminBundle:AdminContactType:delete" }
    methods:  [DELETE]
