ojs_admin_index_index:
    path:     /
    defaults: { _controller: "OjsAdminBundle:AdminIndex:index" }

ojs_admin_index_show:
    path:     /{id}/show
    defaults: { _controller: "OjsAdminBundle:AdminIndex:show" }

ojs_admin_index_new:
    path:     /new
    defaults: { _controller: "OjsAdminBundle:AdminIndex:new" }

ojs_admin_index_create:
    path:     /create
    defaults: { _controller: "OjsAdminBundle:AdminIndex:create" }
    methods:  POST

ojs_admin_index_edit:
    path:     /{id}/edit
    defaults: { _controller: "OjsAdminBundle:AdminIndex:edit" }

ojs_admin_index_update:
    path:     /{id}/update
    defaults: { _controller: "OjsAdminBundle:AdminIndex:update" }
    methods: [PUT]

ojs_admin_index_delete:
    path:     /{id}/delete
    defaults: { _controller: "OjsAdminBundle:AdminIndex:delete" }
    methods: [DELETE]
