ojs_admin_institution_index:
    path:  /
    defaults: { _controller: "OjsAdminBundle:AdminInstitution:index" }

ojs_admin_institution_show:
    path:  /{id}/show
    defaults: { _controller: "OjsAdminBundle:AdminInstitution:show" }

ojs_admin_institution_new:
    path:  /new
    defaults: { _controller: "OjsAdminBundle:AdminInstitution:new" }

ojs_admin_institution_create:
    path:  /create
    defaults: { _controller: "OjsAdminBundle:AdminInstitution:create" }
    methods: [POST]

ojs_admin_institution_edit:
    path:  /{id}/edit
    defaults: { _controller: "OjsAdminBundle:AdminInstitution:edit" }

ojs_admin_institution_update:
    path:  /{id}/update
    defaults: { _controller: "OjsAdminBundle:AdminInstitution:update" }
    methods:  [PUT]

ojs_admin_institution_delete:
    path:  /{id}/delete
    defaults: { _controller: "OjsAdminBundle:AdminInstitution:delete" }
    methods:  [DELETE]
