ojs_admin_language_index:
    path:     /
    defaults: { _controller: "OjsAdminBundle:AdminLanguage:index" }

ojs_admin_language_show:
    path:     /{id}/show
    defaults: { _controller: "OjsAdminBundle:AdminLanguage:show" }

ojs_admin_language_new:
    path:     /new
    defaults: { _controller: "OjsAdminBundle:AdminLanguage:new" }

ojs_admin_language_create:
    path:     /create
    defaults: { _controller: "OjsAdminBundle:AdminLanguage:create" }
    methods: [POST]

ojs_admin_language_edit:
    path:     /{id}/edit
    defaults: { _controller: "OjsAdminBundle:AdminLanguage:edit" }

ojs_admin_language_update:
    path:     /{id}/update
    defaults: { _controller: "OjsAdminBundle:AdminLanguage:update" }
    methods:  [PUT]

ojs_admin_language_delete:
    path:     /{id}/delete
    defaults: { _controller: "OjsAdminBundle:AdminLanguage:delete" }
    methods:  [DELETE]
