ojs_journal_announcement_index:
    path:     /{journalId}/announcement
    defaults: { _controller: "OjsJournalBundle:JournalAnnouncement:index" }

ojs_journal_announcement_new:
    path:     /{journalId}/announcement/new
    defaults: { _controller: "OjsJournalBundle:JournalAnnouncement:new" }

ojs_journal_announcement_create:
    path:     /{journalId}/announcement/create
    defaults: { _controller: "OjsJournalBundle:JournalAnnouncement:create" }
    methods:  [POST]

ojs_journal_announcement_show:
    path:     /{journalId}/announcement/{id}/show
    defaults: { _controller: "OjsJournalBundle:JournalAnnouncement:show" }

ojs_journal_announcement_edit:
    path:     /{journalId}/announcement/{id}/edit
    defaults: { _controller: "OjsJournalBundle:JournalAnnouncement:edit" }

ojs_journal_announcement_update:
    path:     /{journalId}/announcement/{id}/update
    defaults: { _controller: "OjsJournalBundle:JournalAnnouncement:update" }
    methods:  [PUT]

ojs_journal_announcement_delete:
    path:     /{journalId}/announcement/{id}/delete
    defaults: { _controller: "OjsJournalBundle:JournalAnnouncement:delete" }
    methods:  [DELETE]