ojs_journal_article_index:
    path:     /{journalId}/article
    defaults: { _controller: "OjsJournalBundle:Article:index" }

ojs_journal_article_new:
    path:     /{journalId}/article/new
    defaults: { _controller: "OjsJournalBundle:Article:new" }

ojs_journal_article_create:
    path:     /{journalId}/article/create
    defaults: { _controller: "OjsJournalBundle:Article:create" }
    methods:  [POST]

ojs_journal_article_show:
    path:     /{journalId}/article/{id}
    defaults: { _controller: "OjsJournalBundle:Article:show" }

ojs_journal_article_edit:
    path:     /{journalId}/article/{id}/edit
    defaults: { _controller: "OjsJournalBundle:Article:edit" }

ojs_journal_article_update:
    path:     /{journalId}/article/{id}/update
    defaults: { _controller: "OjsJournalBundle:Article:update" }
    methods:  [PUT]

ojs_journal_article_delete:
    path:     /{journalId}/article/{id}/delete
    defaults: { _controller: "OjsJournalBundle:Article:delete" }
    methods:  [DELETE]
