ojs_journal_article_file_index:
    path:     /{journalId}/article/{articleId}/file
    defaults: { _controller: "OjsJournalBundle:ArticleFile:index" }

ojs_journal_article_file_show:
    path:     /{journalId}/article/{articleId}/file/{id}/show
    defaults: { _controller: "OjsJournalBundle:ArticleFile:show" }

ojs_journal_article_file_new:
    path:     /{journalId}/article/{articleId}/file/new
    defaults: { _controller: "OjsJournalBundle:ArticleFile:new" }

ojs_journal_article_file_create:
    path:     /{journalId}/article/{articleId}/file/create/
    defaults: { _controller: "OjsJournalBundle:ArticleFile:create" }
    methods: [POST]

ojs_journal_article_file_edit:
    path:     /{journalId}/article/{articleId}/file/{id}/edit
    defaults: { _controller: "OjsJournalBundle:ArticleFile:edit" }

ojs_journal_article_file_update:
    path:     /{journalId}/article/{articleId}/file/{id}/update
    defaults: { _controller: "OjsJournalBundle:ArticleFile:update" }
    methods:  [PUT]

ojs_journal_article_file_delete:
    path:     /{journalId}/article/{articleId}/file/{id}/delete
    defaults: { _controller: "OjsJournalBundle:ArticleFile:delete" }
    methods:  [DELETE]
