ojs_journal_issue_index:
    path:     /{journalId}/issue
    defaults: { _controller: "OjsJournalBundle:Issue:index" }

ojs_journal_issue_new:
    path:     /{journalId}/issue/new
    defaults: { _controller: "OjsJournalBundle:Issue:new" }

ojs_journal_issue_create:
    path:     /{journalId}/issue/create
    defaults: { _controller: "OjsJournalBundle:Issue:create" }
    methods:  [POST]

ojs_journal_issue_show:
    path:     /{journalId}/issue/{id}
    defaults: { _controller: "OjsJournalBundle:Issue:show" }

ojs_journal_issue_edit:
    path:     /{journalId}/issue/{id}/edit
    defaults: { _controller: "OjsJournalBundle:Issue:edit" }

ojs_journal_issue_update:
    path:     /{journalId}/issue/{id}/update
    defaults: { _controller: "OjsJournalBundle:Issue:update" }
    methods:  [PUT]

ojs_journal_issue_delete:
    path:     /{journalId}/issue/{id}/delete
    defaults: { _controller: "OjsJournalBundle:Issue:delete" }
    methods:  [DELETE]

ojs_journal_issue_arrange:
    path:     /{journalId}/issue/{id}/arrange
    defaults: { _controller: "OjsJournalBundle:Issue:arrange" }

ojs_journal_issue_arrange_sort:
    path:     /{journalId}/issue/{id}/{sectionId}/sort
    defaults: { _controller: "OjsJournalBundle:Issue:arrangeSort" }

ojs_journal_issue_article_add:
    path:     /{journalId}/issue/{id}/add-article/{articleId}
    defaults: { _controller: "OjsJournalBundle:Issue:addArticle" }

ojs_journal_issue_article_remove:
    path:     /{journalId}/issue/{id}/remove-article/{articleId}
    defaults: { _controller: "OjsJournalBundle:Issue:removeArticle" }

ojs_journal_issue_view:
    path:     /{journalId}/issue/{id}/article
    defaults: { _controller: "OjsJournalBundle:Issue:view" }

ojs_journal_issue_make_last:
    path:     /{journalId}/issue/{id}/make-last
    defaults: { _controller: "OjsJournalBundle:Issue:makeLastIssue" }
