ojs_journal_journal_contact_index:
    path:  /{journalId}/contact/
    defaults: { _controller: "OjsJournalBundle:JournalContact:index" }

ojs_journal_journal_contact_sort:
    path:     /{journalId}/contact/sort
    defaults: { _controller: "OjsJournalBundle:JournalContact:sort" }

ojs_journal_journal_contact_show:
    path:  /{journalId}/contact/{id}/show
    defaults: { _controller: "OjsJournalBundle:JournalContact:show" }

ojs_journal_journal_contact_new:
    path:  /{journalId}/contact/new
    defaults: { _controller: "OjsJournalBundle:JournalContact:new" }

ojs_journal_journal_contact_create:
    path:  /{journalId}/contact/create
    defaults: { _controller: "OjsJournalBundle:JournalContact:create" }
    methods: [POST]

ojs_journal_journal_contact_edit:
    path:  /{journalId}/contact/{id}/edit
    defaults: { _controller: "OjsJournalBundle:JournalContact:edit" }

ojs_journal_journal_contact_update:
    path:  /{journalId}/contact/{id}/update
    defaults: { _controller: "OjsJournalBundle:JournalContact:update" }
    methods: [PUT]

ojs_journal_journal_contact_delete:
    path:  /{journalId}/contact/{id}/delete
    defaults: { _controller: "OjsJournalBundle:JournalContact:delete" }
    methods: [DELETE]
