ojs_journal_theme_index:
    path:     /{journalId}/theme/
    defaults: { _controller: "OjsJournalBundle:JournalTheme:index" }

ojs_journal_theme_show:
    path:     /{journalId}/theme/{id}/show
    defaults: { _controller: "OjsJournalBundle:JournalTheme:show" }

ojs_journal_theme_new:
    path:     /{journalId}/theme/new
    defaults: { _controller: "OjsJournalBundle:JournalTheme:new" }

ojs_journal_theme_create:
    path:     /{journalId}/theme/create
    defaults: { _controller: "OjsJournalBundle:JournalTheme:create" }
    methods: [POST]

ojs_journal_theme_edit:
    path:     /{journalId}/theme/{id}/edit
    defaults: { _controller: "OjsJournalBundle:JournalTheme:edit" }

ojs_journal_theme_update:
    path:     /{journalId}/theme/{id}/update
    defaults: { _controller: "OjsJournalBundle:JournalTheme:update" }
    methods: [PUT]

ojs_journal_theme_delete:
    path:     /{journalId}/theme/{id}/delete
    defaults: { _controller: "OjsJournalBundle:JournalTheme:delete" }
    methods: [DELETE]

ojs_journal_theme_globals:
    path:     /{journalId}/theme/global-themes
    defaults: { _controller: "OjsJournalBundle:JournalTheme:globalThemes" }

ojs_journal_global_theme_clone:
    path:     /{journalId}/theme/{id}/clone
    defaults: { _controller: "OjsJournalBundle:JournalTheme:cloneGlobalTheme" }