issue_manager_index:
    pattern:  /issues
    defaults: { _controller: OjsManagerBundle:IssueManager:index }

    
issue_manager_issue_edit:
    pattern:  /issue/{issueId}/edit
    defaults: { _controller: OjsManagerBundle:IssueManager:edit }

issue_manager_issue_arrange:
    pattern:  /issue/{issueId}/arrange
    defaults: { _controller: OjsManagerBundle:IssueManager:arrange }

issue_manager_issue_add_article:
    pattern:  /issue/{id}/addArticle/{articleId}
    defaults: { _controller: OjsManagerBundle:IssueManager:addArticle }
    
issue_manager_issue_remove_article:
    pattern:  /issue/{id}/removeArticle/{articleId}
    defaults: { _controller: OjsManagerBundle:IssueManager:removeArticle }
    
issue_manager_issue_moveup_article:
    pattern:  /issue/{id}/moveArticleUp/{articleId}
    defaults: { _controller: OjsManagerBundle:IssueManager:moveArticleUp }
    
issue_manager_issue_movedown_article:
    pattern:  /issue/{id}/moveArticleDown/{articleId}
    defaults: { _controller: OjsManagerBundle:IssueManager:moveArticleDown }
    
issue_manager_article_move:
    pattern:  /article/{articleId}/toc/move/{direction}
    defaults: { _controller: OjsManagerBundle:IssueManager:move }

issue_manager_issue_new:
    pattern:  /issue/new
    defaults: { _controller: OjsManagerBundle:IssueManager:new }
    
issue_manager_issue_view:
    pattern:  /issue/{issueId}
    defaults: { _controller: OjsManagerBundle:IssueManager:view }



 